rustic: ENC[AES256_GCM,data:BX02oTejsYOoHBI=,iv:NHuqnSibmY/RkJrSUWm0TbgG45iSdjso9ABI8SGqUTg=,tag:XJsnyxfZlNgl1FO7gjwoIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Uit0RVpUeit5TTBXQUd3
            OG9xTUxIU0o3K1NpN3VBMlNTZ05LT3RFK3dRCnZ5OXhGS0o2K1YrQTBXV21tMXgw
            SEVsNjU2cHQxOTJTZ0dkWjA5Sis4SVEKLS0tIGNobnV2WENqZ3ZGMWhTdDNzTElR
            R2hvVDhrOU5FcGVJTWdBSzBReTdYS0UK10tHmEHoXsdNKsdbLLMe28y6MYgvfzCX
            pxomYYMYRfy8DCyLBX50YP++47fTUUb+tY+cGXNvvNvCW6fgYFo3lQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w6xjgskpxnlpleswumdhtt7x8zx35qn329yz3x7ftqdcmcxrrvnqnuf9d6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWOWtneGFlQXQzUjdPMUJh
            YXIzdFJhdUtMcjdYMGhsT3MxZmhicG8xQ0dJCnR1V2ZEdFYrcWMrQlFCa1VMdWIr
            a2h4ZHJaYk9VSTBxWC95aEZtbXc0amMKLS0tIHJ1Qk91RWk2cTMvdXdQQTRwWHhj
            NVBxSk9YQWVrRi85WHhxbVE0Y3BMaEUKjp9LEdjkgcHhbQR9WcVnd2z/nHyaSeSU
            d9rRK/V97WRG6Bb+e6ljVEG7abZu1ni882ztz5Oa8DtLraI2+UGjCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-12T10:24:40Z"
    mac: ENC[AES256_GCM,data:CjXgBwBPVcdER8rJC9S3QXMoSf/5cSfebxfusBEAoFzdQg1w6USN7inFC+xBVrjpoVKa295k5I+CRqaECOl/E2tmRcftbl7d49XnAOk2P4Cx7IfsUbUWPjJER07c43Nktehxiw8Okh1uw5v85UQ1VUmzpWFcwgNRsHxHEwQQ5lc=,iv:JHTol2haBhvEaaJ+c+y35gV59VyliI2gN7mY+Q9M0Ac=,tag:xwbRi3WTbOh09VTcoK2Gbg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
