rustic: ENC[AES256_GCM,data:a3X+D7ObcZBv7Tk=,iv:NHuqnSibmY/RkJrSUWm0TbgG45iSdjso9ABI8SGqUTg=,tag:e29ruqTWklHZ3SwXK7SGMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNW9GdktpZUpyVHZQMDE1
            am5XSkZSWVVkSHRYSmpTQ0pmMDNQS3psQTFzCnlaeVRxbFcrbGFNMGxBbGZvWkts
            UjhkZlQ4TXorNk5zc3RJc1V0TFZaMzQKLS0tIHVpYXdUZjJoT3Vlc3pvR2NxRE9o
            ams1OHlENm85MVF4cE0vNSt1ckZJdGcKQ/dTC5XIDL8mEcvNQTJoFzjQYA8IwvvC
            cbinUL18R+RAhCktS7cbyMwjtLG5NblOL5B+POOpNgDeWtJaq0937g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w6xjgskpxnlpleswumdhtt7x8zx35qn329yz3x7ftqdcmcxrrvnqnuf9d6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aS9SaUt3RnN2MlJQeTBH
            VWxlVStSb2orOGhzRzdFalVRUEovTktlUldnCmdvellXRFRoVmwrTnhGSFZNWm56
            bjk3aEVHRW83Wi9kQklvTityL3JTSVUKLS0tIGZBZkRJTFdpODFhRThNcVFmaFFh
            UGR1RlBlb0Z3WFlGVTB4QldNVzRNQ1UKwQwDjfOrZFx9fRIOwTnAfhdjCJElcNnm
            qi1sMgOGTcqYkc2D7yOYZbij3St2ZnAx69sRW6yE5oYAvpDNcGd9LQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-25T09:55:31Z"
    mac: ENC[AES256_GCM,data:ItgT1OSps2EtJfRyd371MlrMpgrpZQOkx8TXToqqFTsQmkZdx5nKvYmzt0fyqnKOdpLLaMS1NxVRAZ2U8CbST1Uc1rwa4G7xYPk60EagDpO75Dl6Aevs4cd28NRTo/aVtkE5ExLpmf4jygpkghJRc5kEVj6pNDVU1/xwKGB1fFY=,iv:vf5ZDkQWgIt15JyPhtYSEq6TQBFx4Fpvkgvt2EY93mA=,tag:Q059RZuvuVkfmVWxVqkTwg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
