rustic: ENC[AES256_GCM,data:0gI0lIdOrj/1LGg=,iv:NHuqnSibmY/RkJrSUWm0TbgG45iSdjso9ABI8SGqUTg=,tag:/SmXXL/RU/4AjnuFs7E4/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Y2xFNStKTmt4YlRFdTJV
            RmczR2tjUEoxa3BkcWNqT1luN1FrWFdDazNVCjc1cUdiVGZZUUYzLy9NdlFmYWRL
            M2lNMkNIYkxnR3NIejEvR04xWFl4Mm8KLS0tIExjQlNrZ1JVTlUrNmljWFIxY3hN
            Ym8vbTF2NEFhSWVpQ1YrZE9FUHFTbUkKPuuPvIzC5Hch5RNtU1eNc7RmmsY+lEou
            E0aIitp3zW+pPHxtXJnOu0QpLE485Jr6BUzz7VwxMSpkO+niYDiGzQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w6xjgskpxnlpleswumdhtt7x8zx35qn329yz3x7ftqdcmcxrrvnqnuf9d6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMU1lNlcremJiTXFqZ2x6
            M0xyTnZlNFlWTGw1TzRCZ2ltU0VoMDM3Qmo0CkZ0V0EyOVgxTllHU1VKRTRkYUxa
            OWdHMGtBWVUvdWxsOHIyNHhrQ1ZraHMKLS0tIForYXRXZi90UC9yTzR0V2x3Yncv
            bnNqbDRFWWN4TTB6SE55Qnh3RlhIWWcKhWZGgHU+ucCaaTiY6DJ7ZF08nHGrEoio
            AagCusPIXh/5EIC/MqXAicuZvllC4R31pzinnQhLA2XH/e7E7q68aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-16T15:28:03Z"
    mac: ENC[AES256_GCM,data:XE4hzHc64FtuAx4VZNxpil3Gmlwl387VlYeKpP68GwIw16PVA6oqYwq+unpKN9Jj+6ij7tHUfzYfeGre0X0p5VbpUca7jZ+aqYqDA5/kVYUxDetuTkwLQOqT+HhSQoFw8wJQ5YHOry1iGiYcnt/zdKD3OpVFLF4BslrP5YaBbfs=,iv:zGf2rc7NIVRkFWfb+kSZBv/Y1N+R9vL6NXVP9sLk0D4=,tag:wNkL1yhA6ElrLZYbO6PVtg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
