rustic: ENC[AES256_GCM,data:0TTYce2wUFyDHps=,iv:NHuqnSibmY/RkJrSUWm0TbgG45iSdjso9ABI8SGqUTg=,tag:sgBmde6XkTi/Hb29QHmcBQ==,type:str]
gh_hosts: ENC[AES256_GCM,data:1Rq4KVtnU9R5iB5Head/H5gThKtc3BXlMUlawdhuw6Jzy4mC4soRM+zB9Tpq6pfXP6T16NXcI5WmwLqPNy8+dvBleQztD4GVJMOEEhlzS5zftTAoEGQoCAGlUBdhpjNeXa5YQijd,iv:iFRFCY7y00O3hTi2Ba7stqfVAGPm9M4QRgpbI7X5u1E=,tag:H1m8qzK88ZEhcPshYKWBHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTUd3YlRwNUYvM0dzbnk5
            YTdCb2ZuNTZxYjVhdkdGN0pMS1pIV1p6QlZnCkpqQnBFWloyQVpGc255SS9QQktR
            aHJLNUhkQ0Z4RTh1Z1VQYi8yQm5ldlUKLS0tIGlaV1BuR0xSNnVHTFNUdmh3a2Qy
            enV6ZUEyVWhGN2ZWdERCbGd1dlV1S3MKf6GugpCjvKAlJ6LnZpfoKIcQ/iv4PPlf
            Ako2nLfjF98ozSK9jZpq7zcmtH7F9vfAW7Pfi5d7aAb7046yAvDmNQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w6xjgskpxnlpleswumdhtt7x8zx35qn329yz3x7ftqdcmcxrrvnqnuf9d6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3SFR2QnQrV05BT3BGck04
            NVA5TDZKUU9wNXVBNXRMQmpUS1RRalhoYVI4CmZUd1VRS3ZVbmZ6WG5HL3FpM2J3
            cHNwbk5DNWFMbHlqNjhvVzRDMnpQcE0KLS0tIHhiZlU3TEJySk9iKzlhUTFsSmpq
            c2gwMHdZVElHMStjRm12M1B4TjN6QjAK54TN5xcjYl+GESRqoP4Dbd5sSL7fZJff
            /lTashrjICIqMiAuEx9KRoFHLkLQKBf7M7VNxY8ikmE+JEf7V9Ug9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-10T15:44:42Z"
    mac: ENC[AES256_GCM,data:0PfXbT/fpfyFyO2pnjh7DjoeR+OdcViKGauY0Qeuc/I2c701J7c8fQgHLoSBW19SCeNhZ6W+T2e2aDCSNOFOI35w2/lAd/pySQvji9ejSlPIHU9sbfuM7ve1Di1BEYoIaBKPGOHAlOGFMjyyKYFlg54D6+mV9RjEg+dhiz6P6y0=,iv:GqShw/7TtCpcwUSZFu/y99kk+TIxO3+2GnnVhpUhzTU=,tag:iiJ5drRavnLBe02Gv7g5tA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
