rustic: ENC[AES256_GCM,data:65GvoqMLchYAY7U=,iv:NHuqnSibmY/RkJrSUWm0TbgG45iSdjso9ABI8SGqUTg=,tag:YmO4knH7TxcYryMCvhIiHg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMOGZFRE5BcUxkQ3hnM0pl
            MlRxTjgrSVZHSTVMUFh6RWdGckk3b2gzdEQwCmtEeFo5YkZXdEM5VWJPUzFBTWVK
            U1lkWUF4T1IwRVAwVW5teXY3STY4TTQKLS0tIEZjQWhLamlaYzA5aFZDeFN5NTg1
            MlFOYUJwZjZXNDBNMUtsR3JRZHVkNW8KO/OLNhFXcjXqyCos8J+WedHl0y/MEnNW
            GnHX2OXgYaLgWaKB7k9BGmXqJx872Qx0GDpNtKuPcO9MVJ6VeYZbeA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpVVBFbFR1QTloQVUzNnRl
            d2dRYlJGMlRBRDVSYUZRNjVrdzRTT0dDMkNVCmxIYlRkOUZaRjRoSGVYdy9ndXgr
            VlpMQTFleFVWYU5sais5RElxNG81d00KLS0tIFNFVTFZQ21tZGFVWXpPZGtXYmNS
            Q25YSVQ0R3BNN0FuZXRyV2pyekc3bmcKjUdICrarUkAZ2/gDZk5WUew8bcz+5HCF
            TxeX8jAdVncQghB0KXAxP8t9yVaJQ3nGeKjVQabOClbW+tLeo815Sw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w6xjgskpxnlpleswumdhtt7x8zx35qn329yz3x7ftqdcmcxrrvnqnuf9d6
    lastmodified: "2026-08-23T09:34:36Z"
    mac: ENC[AES256_GCM,data:jtToFAhs1J0xeYql6c2aZhPdCOi7F0EWLtcKfIBLSSapvptxCd8WfyEXj2B9wFOjPXEvM8jv/oiplnKmJVY4Akz9V09h0jJqjt27hOq4Br1BT+/4bo2bIaslDXzg4MVofOHgAajrzHjJTA54DyJcSHS7B6bNoxH7qCoCy9FLS7g=,iv:sMqRI2ss7SSJyNwyIyG0uToO7oXQXLSn31uoILcMlOM=,tag:jaQ7KrWoDtuZDKwFFedwCQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.8.1
