rustic: ENC[AES256_GCM,data:QK9mADaNKklucd0=,iv:NHuqnSibmY/RkJrSUWm0TbgG45iSdjso9ABI8SGqUTg=,tag:ndJxlYQ+X0Zb4jIxLRysvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2KzZIbTZ3WlNhZGVSU29v
            anBVeHUwZTFHSk9xQ25jY0c2S0VIaGo3aDBjCldGb2JUd1p4SVVqUHJpUGhGKzFX
            SS9DNUdXMGdEMFFpYzBlbHJOQ1NTUVUKLS0tIEVYVmNuVUlZN2xUdnhISEMxRncv
            MWh4dzd2anJjdHRhZjV1cGRxLzJCTFEKkKpygRo8CQQTQLzFS7wicEfDFSSdbAo9
            coSDMYHMVhvIw8PwLCwPjAGXhEYhgIdM/ipv1h/O2oCHIWBFWYh8Ig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w6xjgskpxnlpleswumdhtt7x8zx35qn329yz3x7ftqdcmcxrrvnqnuf9d6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaUN1OUkxMFVlVnUrM3Bo
            OE1RU2paTkEyUXE1QVc3MXdhRFQrMTVoUEhnCnhsR1hhNnJJMlY3VDNHTEp3L055
            eG5TSlU5NXlBWm1FenMvdDcyRk14RTQKLS0tIHlwUXNoMndrUzRjbHNieWJqanRp
            aVdOcEpoejR5UklreTVyQjIreERvN1kK93GhDqvbHXZqXCo5L/XhJyEdypSxE5Em
            h4Uw3QdvX3wH4hcEVblrkqEh7SjZm90TLmV8Y3depj0URZm9gHqg2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T08:11:43Z"
    mac: ENC[AES256_GCM,data:MBNbxnG5Gf9Xd4eaPzHWWAB4SatXkZsGO/PNRsRORe0l3QvDY8c/bnh1l6ImBRW3Z0QxsZot0knXu7w4ZYVFPdvaSLdsb+yT9WeVcrqqz6lFX+3qu/W3iekj/4qKXE553i+dL8w3LzT+2gWtYv4+oTtPQn1iBtcmsYuL1K7kA1s=,iv:3N6vlPOnGiSIA+6cknRom1H0oki0f1xW4z0pCI8pI/U=,tag:BMcV2nm581OoHCp+Okw/Bg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
