rustic: ENC[AES256_GCM,data:/4A8nJgzxdUyOiI=,iv:NHuqnSibmY/RkJrSUWm0TbgG45iSdjso9ABI8SGqUTg=,tag:XEXijWnTbnZSFECTos6PUA==,type:str]
sops:
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MzF4WWY3QUxSQUFHMVlI
            dDYrRTNBa3gwQXNYUGJNS1BCSmV0bTNFWVRVClRYcm5INWNlRlZWVGlPR2VWZXh3
            bEFVNHk3eUJJWmhsazhSdGZDU2k2NTgKLS0tIE5QV2hWM0F0RklUazZXK1pJWnJZ
            SVFyYndiZlZqMnNZelZFcVUyaW1lalkKSdWXzgSCW0sWAWkzHAvoU4yvtMmxLmQg
            m1cc9MkEDjVJ33Si6Y5I8iTNTndtBRGthoS+XFsAPnIt4680DLVc/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w6xjgskpxnlpleswumdhtt7x8zx35qn329yz3x7ftqdcmcxrrvnqnuf9d6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWandaY01YMFhzNXB1UVFV
            bENkbHg1ZmRJdElJdE1pK3pvLzd0VXg5T2tZCms2WWREWnUvekpEYmxOanlJWk9T
            NG9kT2VoSGs1eTdyMThpamNTVzJTWk0KLS0tIFpIT0tBcVZiemdsREtCZ1lJT3dz
            Ly9EaGNHaFA1UTlKNFhMbTVPV1V0QjgKd5H9ZXc6cjB4JFP7Z6H1EyW1+NtEmG6a
            5ALBJrqID20tbYvdNDhc6L+WKe7x+j3MdsAp8y95nEfhoHnfEGiCgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T22:56:24Z"
    mac: ENC[AES256_GCM,data:/QGe05hhhpuU9I9fdAESYFOQLMQQYkTaYoVZWH1puJz4jbQ8r5XuYToWL3ECNyVfVzaJ8FPTSvxGyaYrvrhgzUZ5oL1/lBFWlODRJgPfZiHQ2ga2kDh0hnCDmoTzsqiOXeUEVmTLS2DPkIPdYP9SB3kg6VOPmeFcRyZnK93yfHA=,iv:AgkB7rl32rrHe7tP5NRh0+00b76sqK1FYNtHyukDRTI=,tag:4NEpyqpuiqhjTCd3qKnYlA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.8.1
