rustic: ENC[AES256_GCM,data:fCXbK3DCj0s3PQI=,iv:NHuqnSibmY/RkJrSUWm0TbgG45iSdjso9ABI8SGqUTg=,tag:vE7uKbmypxnT+KIIRnTz+A==,type:str]
sops:
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UG1zbnFCK0JJbkFHYkc5
            ZWV3SGlQTU5lZ3JsZzF6aXl6eURsV0xZSEZBCjV4dktLMUh4Rk84SXFBVFh0RDBF
            ck9FTEZUTGcyYlQvdVk3cWNBWkhTUkkKLS0tIDVRb1cwbGQ3QzNMS0tjQjBhZkNu
            MDFDUXZqV2lxekRVYmdVdThVemhkYjgKu54AJAM/z/f/ZxfyJ4tx5V6i7622Gma2
            aD5eDLor5yaWfZ/OOvwSLXm0DK6MGIeczksKxNwcXzjm76Q2x8ZUxg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w6xjgskpxnlpleswumdhtt7x8zx35qn329yz3x7ftqdcmcxrrvnqnuf9d6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUk9wQjd6VmpURE9seDZl
            dzdZNGttNUJNWnFvNlVzQk5LRWVzY2MzcEdjCkFSOTVydVNzOUFIck84cEJib1pq
            VEZqYUJoTlVqL3ZLVzdRWWEySFFaT28KLS0tIEdWc1J6ZmI3cEV6WGs5d2pVZWhu
            YkN2Q2FnQzB1RzVGTzZ5eXFGemFGQTAKjUFvIwaquPKaP0om9l0yN0LO73m+loo3
            GiGLKjryICSKFbLhjwa+J7BdvIzyJXQH5SZ57CsIBjkdB7TLbrVQcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T21:46:49Z"
    mac: ENC[AES256_GCM,data:qei8uNMQZbwbZEX+DjEQttyJpD6ofcHoN9SYF9fEdjrqcbfF7aqK/FPaxI/uYwC6i5+Hd8/tHvRUMKdvJuUQFqBk9RZrVz+BT9q80YSVOv/XFxtFvnPSNDLOMkBIlP3KL6JNxECBcD4fFPn0I1ILAvXV8ekuFCkIzFSQge1157I=,iv:uUKLMc7LLRHfauCov/IOIG2LFmmOpZ3+q3Tnkj3xWeM=,tag:r/bR9GI3zJUBg0OTNCQEMg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.8.1
