rustic: ENC[AES256_GCM,data:0gI0lIdOrj/1LGg=,iv:NHuqnSibmY/RkJrSUWm0TbgG45iSdjso9ABI8SGqUTg=,tag:/SmXXL/RU/4AjnuFs7E4/w==,type:str]
gh_hosts: ENC[AES256_GCM,data:lLbAynTwguC/xj24/PSyI/iZb25AkU4Kp3aW1CYp2Mou7qg1BfULQPI6fOBhlHgUq6DZUQoRNqs1uktgr3iV5QJAF6tXSo0poVpssTvhvuregR3eXvqx+dn3QUCjMZxwuU+a2twb,iv:iFRFCY7y00O3hTi2Ba7stqfVAGPm9M4QRgpbI7X5u1E=,tag:pJaf0h9e2tVd9yEzrA6jVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Y2xFNStKTmt4YlRFdTJV
            RmczR2tjUEoxa3BkcWNqT1luN1FrWFdDazNVCjc1cUdiVGZZUUYzLy9NdlFmYWRL
            M2lNMkNIYkxnR3NIejEvR04xWFl4Mm8KLS0tIExjQlNrZ1JVTlUrNmljWFIxY3hN
            Ym8vbTF2NEFhSWVpQ1YrZE9FUHFTbUkKPuuPvIzC5Hch5RNtU1eNc7RmmsY+lEou
            E0aIitp3zW+pPHxtXJnOu0QpLE485Jr6BUzz7VwxMSpkO+niYDiGzQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w6xjgskpxnlpleswumdhtt7x8zx35qn329yz3x7ftqdcmcxrrvnqnuf9d6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMU1lNlcremJiTXFqZ2x6
            M0xyTnZlNFlWTGw1TzRCZ2ltU0VoMDM3Qmo0CkZ0V0EyOVgxTllHU1VKRTRkYUxa
            OWdHMGtBWVUvdWxsOHIyNHhrQ1ZraHMKLS0tIForYXRXZi90UC9yTzR0V2x3Yncv
            bnNqbDRFWWN4TTB6SE55Qnh3RlhIWWcKhWZGgHU+ucCaaTiY6DJ7ZF08nHGrEoio
            AagCusPIXh/5EIC/MqXAicuZvllC4R31pzinnQhLA2XH/e7E7q68aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-13T06:10:33Z"
    mac: ENC[AES256_GCM,data:bxY2vxPdoeYfBPwI1GfcfuHJHpTm4fBU1VamWAyzathz6CvNYhnxVolom+5aD+GzsHm9N2H2nyfzp/LaAZdt8MERqgTVG96jvI3g/dcqwK8RQcSbB4jk14VQ5Cqqk20FwjZwvVYTM3vkMSUqrrmAZzEHPOW5xmGEfFXL4gzViW0=,iv:Du+NYHoZXBztwkLuKsSuidfTjY1Ku+EkQIwFxzo1zRY=,tag:+4PlzT1ox9r23vd0Odktqg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
