rustic: ENC[AES256_GCM,data:i/K0APGh6RQNRhw=,iv:NHuqnSibmY/RkJrSUWm0TbgG45iSdjso9ABI8SGqUTg=,tag:Mo+/wxLb5jiCSphAi97ERw==,type:str]
sops:
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0azN0eE8wUTY1NVNIUWcv
            QkY1eXlmODBodU5xRTg5US9qR0FMaFBRRENJCllsZ1Z1SmZNSldmOEMrUnA4UDhL
            YTgrTit6UkhsdkN5eUdOZDA4dUViaDQKLS0tIHJnVVV3S3FIVWxLM1hpTDhLeDdZ
            b0FheFJxQU9kVjVBdjFwMWcwSXZWM1EK6yA3ZI2pJzmR49G1eaS90Hqr1hBJL6tU
            09tiO9s3TeLKv/0z11gZRBCFfRytTxEv3ExZjFKiqBiCEqoj16Vhaw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1w6xjgskpxnlpleswumdhtt7x8zx35qn329yz3x7ftqdcmcxrrvnqnuf9d6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQmlNR2pscTR1MTcrQUxI
            cGttVmdsZzNmZi9nYmhvd1NiM3IzQlhnUXp3CjlHb3ZRdVRjZjZlYURteW91YjFI
            QXpOUXYxNytWUVBVMHhScURhM1JhVnMKLS0tIFlITUNmOWsrdldNQ0VOYjNmenFw
            cGdnSlpMWDArQzZ6dXlxS2E1T0Y2dVEKH7+XA9kkh2ly1vL2OGJz81UWKXio2y38
            FPN/LJivgdxM1RZS2H5D+21kwlpMIzHm9ksXA6YqeF7HVQks2H2jYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T07:36:24Z"
    mac: ENC[AES256_GCM,data:6jcGVTJbZc4+SHg+uTyDb6SpYz+HUrf3DaE5QyNB0bRg/Exayv1+qKSFkP2SwKZi49ZKuaUCVkLoxaZnunh/cppSmL2mFdsS7vnNph552kdUc9Wvoy4TLqKAHx3Qfmvo5enu5Se6F75bt4af0LfrLpl+QCm8ieWSVH/OtxO4Oz8=,iv:DjVHBXbtHccx4hHd+meWjqW3GY4Vs2FAWk6alDlqgEM=,tag:WtT63tz183ICGVHl/T6bvw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.8.1
