ssh: ENC[AES256_GCM,data:uGLGfIc+9y5R2/IcEnulT0GlKut5njWoiOZwYoW+KWceW7CS6lphXgxJlWPgoPBny646rFK50iNxI1HCQqG0vAMO2IcnkN6ubi38Ev7BQYAlqOTfOt4Jd1XV8djUNBMHtNqi253IT0ZFYYualxSvIi/a3GQLGsI7EF6XH7YV9N1Cpb5nLHSWUOVDO1UNByFb56aHnmqE4BX587Y4k8NQWTo0PZuqXiXQq9hF5hE75jNxKdSj,iv:5DNSXmbM36qXfawqcmzZMfYq2iuVfw1f+sB6gyMNiAA=,tag:80CMFj0nNtpxPoisDA15Tw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTlQ1RmRtWklTTWJSTHM3
            NGlHRndJVzhBRkxrRTRwaUEyS3BtRUQxZ0NZCkY4OTFKSEhqeGxSQ20renc4WWRC
            QnNGZWxVU0thaVdBR0h5N255RjBYb1UKLS0tIEl6cXd4Q2VTc3JOeFNNVjd2MG5Q
            OVh4UEtyTEZXYUFQL3ZIelQ0VCttZGMKqqWdIn9sTrxRj0wkD6oYyAGzLegMNW1s
            +AcpAZOGJlIPDC4IWx5rlA9l7CLDNE+CYiD2EwgGyv4zhCvmCq/lhQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vr0uq6mwv844yvm8pe7qxjxpqrekgel3lqfzuuqtfzj0ehz3hphqzsxjna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaFRCcHFCUVAyVjFsVlhS
            NUd1cXpIOTdINEMwc2hEZnlraEhyTU5lRXpBCk42UlN6T0RGd0xmU2NyRmJFcm11
            dXYrcDJNSWdKYVpzZWlVekkydzRFclkKLS0tIHNWRVFyYm1PcjVEMVp2MkppVkdv
            cDE1bVVMR3R2dXo3aUd4MEQ1Ym9zVU0K3KApnpMzIa7Rx1R8L7icUA9KtcGyUqVR
            /odYsejy6wYyDabHg6rb9fxEpMTZrt+fxUi5OhTNz85zOvkJPBUUww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-20T12:13:05Z"
    mac: ENC[AES256_GCM,data:LbcG2ioGRJdQqmpYRf7ydLVaK1uwXYVJlEAcLv7YlC19UadZKD0e8waj8hFBs0YTDaqyjrDWPHVQSVDfwdLO7rLUr2+E/Jqtpqw+6VAgD/2nr4VJCpNNNKLCkf0hnRHAAHc2h7cxQNv3HzI94nW38WAK/fNCbouERMmTkYlJoBo=,iv:SEFo15HGPO89N7ImgwBh1YVVEqBSM4nYZU8qEDBAEFA=,tag:C2kksrJ7h44oyKglYd/gCA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1