ssh: ENC[AES256_GCM,data:jIsjWnNyhjdMx4K+XWN+lteX92KJjDSghtLTeSkK+y1iXUXP2lpuGJO94caVyRcFjeeFaNqDA1nAmzHI7dxp5nqn2fMIiwWBpeJEJSgaj3GQcOWJCCscM2zlmCANldTMw5gcxOSM395E7SGhj9bZI4A47HDjS/X5rEMzSQRGRGh/gBjVdxs5ZMk0zDasKSesy/pmUmpgIkXM5KgsYp6nRunj+LLJXEGG0yxQxzWyRKW+TqdW,iv:poHvd4U4dJha27Bqf4hA1pFhna29kO/RnFNjJsflpaA=,tag:RDSXQp0/1rUybrj5xEE1uA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVazVHc1FQcGE4M2QvQndR
            ZHJmWDFvQXVtQ3RURWVWVHRPbTNHblFSUVV3CkZZMEQyWURueW9uUmFTNXBFN3pB
            TWd3ai90emhBUE1aNThGRnRIZ0ticmcKLS0tIENuc3pBZW0zUHFEaE1pendmUU1z
            bll6NTlYOUdvUHBVVit4dnB3U3RZNzAKsCSTmVNxetisS5MGR+pZLNnpx9lIYgku
            bqoDK0x2PLcGYNRTzoopKnkmS76OuPVxo2d2m4cCduMSxwpZb6XVaA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vr0uq6mwv844yvm8pe7qxjxpqrekgel3lqfzuuqtfzj0ehz3hphqzsxjna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBydzlFc3FDcmlFL3ltZ0wr
            bTFnalRPMmY2L1FBdjZENTAwbzB3c1h1Z2tzCnNCYzE4UGQxclZBZGpETnMybHBS
            T2xuMFlHZmRNU2I1YXEvZzhxYkVMTmsKLS0tIGdTZytrS1hIdndETDM0SWloMmFr
            d09ocEdaS3pxSGh5dnRLZHhod0p4VlEKL3Jkd+a/6IcZhkSjUfazcLUfQ3OnI7/B
            OyzBRlyoJJ4wUwBh6ZUBVlVuBd926FjahLZ0kPcdlpjdkQM6q+6Hdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-25T09:55:31Z"
    mac: ENC[AES256_GCM,data:1xqSlK2qOYkSrlUESpcO4q3RGr0Dqhq7AdCVRD3jXp2rpmZBgKJ8Un2PvuEoR8Pq6yeYIqlzs77gxrWFjiglhV7g1akoDOPKgHn0xyt9P5au3/Zu23Yq1AI71advUqc7RkNxljyyRnh354E5BFacK3TAjbqm2zhn9rZx1lsntpc=,iv:dfwwBKmEx/W7rp/hVepgTT9eJepFEl7RB7xN6y+jjUc=,tag:tCseYrKrdHyj+tglJTSjlg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
