ssh: ENC[AES256_GCM,data:jwqYK4PDOL4odbX8rQ/YnRZHS2lW9RkIqfyCIp6pKsITmGtlQPRIF2ok4whXZE7Zrzpj27FDRqrIHO+a0teAzERKbsPaffKAey3A2ZCfYfUMIV+E3K5PSOHufdctNObk0E+VDFl7IiAn7QJriKNhmOpdNtaOY+djKiV56a4yIpzRxstyquruVgA4AsyiD2KROfkhQM1Um9gTsT18OZyE6QMIUJnffdNSTMyCy45qyOr0Xhpe,iv:poHvd4U4dJha27Bqf4hA1pFhna29kO/RnFNjJsflpaA=,tag:9BmxEred7cnUv6xUCQzolQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURUlHMWRBcXZEbm80SnFP
            QTJhaWc5elJNL2ZDRFFyUktjRnhWbEhxU1hFCkNwU2Z6ZkZRQkFZQ2R1ZlJ1anli
            ZExZcnBmUFJPMUNWbTBCR0QxckVBMncKLS0tIHFCOUQ0b3dBM2ZLeVkxVTNNY1FP
            bUhMemRHdnZNaE0ydk0xRGdTZFlqRHMK9m5Plzoi1YjdiYibnWVp7aINr2jdNAJ4
            eUTatof2zp6VycQXaaodRGygIM+GITlQMqCa5XFpZYm6028mpUjKaQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbHF0M3ExV2RnQlMyUlpY
            OG5tSXVmYUc2SUVwcEZLT2lTZnBhM1hucjFzCmZpWFk0Y0MwZ0E5YUkvaFFVQU5Z
            cERLNUo1NGRpYzI5b0VFSFNzQjk5dFkKLS0tIG9CakViRE1GOUQreWFNQnhCSGxI
            bHM1MWlRV2xqTHNXZHZTOXBycTh1Z0kKyoWqP5u+W9zq06jJz3tW9mk+derOo2bZ
            cfu3w/9dRPh2Z8hYZ3WwiupmBq2LpBeqeKRMEge7FiDk8x1Xb6whkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vr0uq6mwv844yvm8pe7qxjxpqrekgel3lqfzuuqtfzj0ehz3hphqzsxjna
    lastmodified: "2026-08-23T09:34:36Z"
    mac: ENC[AES256_GCM,data:Zpqz9u/DlBj/D/OoELml/CsMtYmEyNltocFqc7eHrBkpoQHjpGkistjTrbXCevufoFT9PcW9aJkAhIyEkGLAuJL04NtslPAGyw2xy7wt+3um42hy3JWsGEtSxc66WFCxSmymSId0b0L2+JhtvUx8T1VsA57AIGu7IwufySqknyw=,iv:kQNu9vcNPKlHEKOsxdCUCgU2qBQGKP20W4BYjUJMKOk=,tag:WEeGVbgQRTd4r66/+2O4dA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.9.1
