ssh: ENC[AES256_GCM,data:1piCN4mFAU9cJXkag+MQ6t1XnaKg8FOvd2vf9Q4EhdlEJWNqkdepy7bZu2yQb71TWdVqtY7ctKyDWbrjgrRKryJs1LMnIrsCfkjsfAGogBUdpcaYkIfi2huVnLyAB/qZG3NGYqaWpuZXEZMZQD5NWOyY1hZb3sXVV6macu8PCBbQFl2vz+0ZssKXSphrJcgxyPF6TpNJ4ql9WYjA+g3tQMlOdQEgJ+v4zFCheqc/cpvP/sV2,iv:poHvd4U4dJha27Bqf4hA1pFhna29kO/RnFNjJsflpaA=,tag:Ph2JnUD4hitPUvGUZgZY+g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtR2lNeVBuU2Z0WDd2Uytr
            UkVCTUJZMDZUWFdGVmp1cG5saHZFWjlRK2x3CllLOHhQQ2Q2cnlXM1FFVzVnWDRF
            cGhOYWdXWG9sQUIwaFdxRUFNUmtQNXMKLS0tIFcrMzcvSkZnOWpLdjMzR0JXR21n
            VlMxUTA0emZhYVZvenllTGl0WmRvODgKlD476Ysv364IcPABFXH0I+CwLIa0xZ6h
            uhD+zb0Ea0rvrevbifFofi2bI0YN6s6OiTgoEa+UCUL7zTJNgvR9YA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vr0uq6mwv844yvm8pe7qxjxpqrekgel3lqfzuuqtfzj0ehz3hphqzsxjna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNcElzVmJjeWxYOUZOVDlp
            S0Z2Y0Q1enBGanhyTENUSmFRVGtlM1lWeGpZCkdqcTBYWUdLQnJWMXlxV0pOem9M
            L0RKa1Q3YmFMWk1BTzNxTFBsRElkcU0KLS0tIEdDb3RVR09uSWdCQ3BkR2hNTGpv
            b3cvUGNPYnc3aVY2SExFUEI1ZngzYXcKUptdyK0c5amD9mfXfZOu1IwlLeDqacW2
            wLlrabrv17jatrfiW7Ow0SVt7yRNj9NLeYOO5DWB7qj+FIkioxiNZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-12T10:24:40Z"
    mac: ENC[AES256_GCM,data:MpQENnVZ0nRy802BSi0wYlxm5Xmd6cDOgVEFnn4xndm+JdZiWLP4Or6QWKoqBwwVuwWIYC3pgwhW7zSIIbNOazAVK12BVsCAckaV4zMuw3MMJE0LqKQaAUlURmnLCId0Om4tGRJdXFZjw47spI76wZ70DJQVKpemrI7qBEkMypk=,iv:4ml2v2TXmmgsh1560hRC7MzwR5nmg5PCIIeNs0fA2XE=,tag:slp6EI/h1f7CTNN3irWZfg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
