ssh: ENC[AES256_GCM,data:ZPaI5b0YGNqSDrlBmH4uuMFq5kUpT011V0Ud+0Qz+qItYULEowLJMJIwvZh0fhvtgxJOTirSKovsDifo6K0CKUnEhuwpOmlLDaEmLjJnwhZwT9nM/p2ynHrcstadwsGF4ldS+v8FSM4PSSbOmurYpC0C2rmTsJfYuyg8uemS1LugWI8OTvRjYiL/Ol1sdXZpdErr2XVKAJgZeTcJM82hUil7e6am7kq+bPlUwktjl/AfX3e+,iv:poHvd4U4dJha27Bqf4hA1pFhna29kO/RnFNjJsflpaA=,tag:H+8WyEFVj4ySfMT4ST39VQ==,type:str]
sops:
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaDBXSnZRbTJjWHc2RDlh
            K250ajJqZUptSkRBRnVXNTJscUpNU21GZ0RvCnZycnc5S3A1MCs5MFc4L1FFT0pH
            d0lYSXducjBuMmNaVFB2TlFMWWhNOWMKLS0tIGJSa1hKSDBiNklFYkJjRHpGT1lv
            SEVFVjhDRlFra1FTL1VxZE44R3JMeWcKjhgbWk5HPR+dJheA4pxevfcb/JSmkP5z
            BehoKHjfVFqazSR7aLw5jU+pGdnkopZgU2n+6XsP+t84Uw6/hCgbJQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vr0uq6mwv844yvm8pe7qxjxpqrekgel3lqfzuuqtfzj0ehz3hphqzsxjna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dHFnc0Y5dUovYldUUElC
            by9uaURFQnFJQW9iVUhxSVdDRFhqTzJ6WGdRClY4UjdoKzdneDF4cityYzR1YjAx
            UlJXVjN2N0N2VUkwSDJyTFAydTBJODQKLS0tIHo5T1l1UkF4MlBrcUhEMkMyM0Zl
            blRwbFpUU2lFZStvZVordThWVXZ2T1UKVnl8utfFVhx6xxQS2stOu7uH/7Cus3DR
            CnN8I1Ni8mprHpYMQhcUTlSM/cTuEzB0oX3bIrfhG92sHTnIF0mblg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T21:46:49Z"
    mac: ENC[AES256_GCM,data:Mgh02A/4awqSw6MUsRGQVpwG5PBXKk2g68LZm5demwsQ6I+pR4TKRYDRk0mQOwCBStCLHW4htRfeNlWu5gCiIxqGTsWEiKu41qYrM5yaDm1fmBbQe/pICdvijE/Cx0bZIq2s8s8DiCiVgZSTCOizg6C5WvOzl7g1EuQryF9ORcQ=,iv:K/0CF2W7ENTVetv4cjmApLrE6MGp7Oes6nMB0x2kopc=,tag:7t560otaVe9DL0RE5vMYLQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.9.1
