ssh: ENC[AES256_GCM,data:8/riul4w78qAGpURN+jqiPvnx4c69MczJD4J7PvJCds7YzN3n7E2BoMm4kwkK099GN85Ab1w47nw1jgmECFs/nR5fMjx3jkEUAlch4M1Pqbpbpz/yKps1NwznnJB/dOGBCDX6ASKKu4afyXvVccO3FQpCbh9kjDwohNOA8IZVtyNbFc30zEHDnVqq9VRM0Js3QQ29CytCKVaX1SYDU4vGnL0EkxxL7rP1EIiV7QbqEgw7Fht,iv:poHvd4U4dJha27Bqf4hA1pFhna29kO/RnFNjJsflpaA=,tag:RcCHQ61LmaCRkJR0adfWRw==,type:str]
sops:
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBabFE0cnlXWmlPNHNrTWlM
            cXBaeFBUcGZOZ0VHeEhRYjUvRk9laXV5aTFVClBaKzhWdTl0SVNYRmRRaS84dWlP
            QkhaMVhmUFNoQ0ZPV2NZdlBMZW9VN1kKLS0tIDR5MTBvUEl4elorN2tBZENSMjNv
            cmh0a1JSbVJkR3FPVnZHZ2FIZnYwNzgK6rK0tUPebNp+c9Nd0Ci55YG/kSUhMbOg
            RAoI3ZmTQhYE5aGTKhZGhzTreXo/OsnsSXIi+CCDFA1UrOrXfha+4w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vr0uq6mwv844yvm8pe7qxjxpqrekgel3lqfzuuqtfzj0ehz3hphqzsxjna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YmpJNVZSSnU1ZmhjQWFu
            VzdaYlA3Y1RDR3BCbzFNYU1CMGY3WHpMZG5jCmdKTnoyYmZnRXc5Mkh6cEVUSGl5
            QWlKSUxleVhaR2JUcnBJVkUzRFVXcG8KLS0tIG9LcUtCSWVsWGZnekRDdmRTeEhp
            b2RSRURVczdYNCtGakpnd1QwaEFrc00K1PZK0ffHa6h2VHZDobVp0fx2SWYK6g0r
            3OXujmCiFqi4kbv8LJxQwQtLQcfo1KycwD7M/gBLRL26LpxE04+Sog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T22:56:24Z"
    mac: ENC[AES256_GCM,data:bHSUq4FRToh3UTVIkkwMpT7L3brjx+N35sw38CoX/d0ug6BDndxfaPztSMMJAWxv9UoN/TGP2iutpoqbO5JwXDGTR+WrKS9GfjSU2mWB0OCSmYGZervhnh6NgxgeQWiIHTLmnbNJzwlrHN/VAfexvp0CswQo5KM92bsuEl+cPF8=,iv:REVyztWmsXV5AmhyWo8Lp7vnIqsxpbUYlc33PjIV5Yw=,tag:k1xch0bGFFsQFbK1l21eiA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.9.1
