ssh: ENC[AES256_GCM,data:X0m5YkuFHljTCAOOwjdgtYd6PmNyznjPZ95gZWyps7H5drrxiQlt7FiFBvXO5gcggXIkGf2hMCFlfDtNHHlfXjzDLx1bc45lPduuQe53qBVoj1kutFHhJtCj/ttfVcUgHVm65NAWy7gFaccXrY/xcY8HBnOQUbk1TVSIngzIThFFAHvTqMRjuzxEQqpevSloWP/ItJcRqlPt80opCrD8iv0dpOGWRbBMS2p0o8ynFAySmJIs,iv:Z99RVmMuDZvFJP/heCsdxIZd7uV4+lBfBvXMasBb2Yk=,tag:3OJgUL/AWESRHUXlB05gDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNzkwZkVJc1dDY3VTQXpy
            U0xORFhibHNaZkdGbno2c244UkFlZFlOWUUwCkhUUkowemhzN1ZySzRLSDl2aDBS
            M0JRTUZVUFIxemZrZEprWmphOGNpNXcKLS0tIEllTjA3SkszajlLV0lobVRmNkpa
            V0VZMktqbm5YV2RyWkUrMzFpZUdBd0kKEjwAbf8MUTxY89VPINxOw6mdY66DzUJs
            VY7hbMmDZ/9Rw1RFIx93H5U4M435imr+4m3MX4gXO/VGH95RtoFtSQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vr0uq6mwv844yvm8pe7qxjxpqrekgel3lqfzuuqtfzj0ehz3hphqzsxjna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQkNSaUhyMEVLN0VwZ3Ax
            UkFadjhKaThnYkt6UVA1VUhIeXpPNWpUVkJJCmh4TG80VTRwV2lnTDFRUlNpWERq
            cnpKRUltUlB1Rm1hby9lMm1NSlM5SUkKLS0tIFRGOHJvQVVIQnJrNjhobUIwT2FR
            b3FRZ1ltcXkyN080UndZT3ZkZVNSRzgKlfe+kFXYc9y7jvGXj7nwVIBrfPQVI8Ke
            WXRGvmmcm52dEqbcppcGcNx9u4jckDKiCQ6YeaDR9/U/cyHsincmhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T08:11:43Z"
    mac: ENC[AES256_GCM,data:9NsFvPhM0XZx9+63uY+tt7aoARQkRpLeIupfWBPck+BcgB37u1duvs/YwazCNVBF7y3QF6aNz9WLW4uCmJFyvxhuq6pY+Xf9dM7ccVtLizfUjtgWTn6k6aFbcfJP+BEXKqDZHHCvtg7ixRI7Y8OrkY/wYQwCedihu5k2eCFp4eI=,iv:h4OAZXkxVkljYNtxEmUNHxwomVZ1IXNhVH2Yu2WUTCA=,tag:rnCd14bHerVtk25ARzHBOg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
