ssh: ENC[AES256_GCM,data:pFajcA5CBZ0jbFqsRf5vbcueZDuYjv3TIkWiOmfZsfuIWo17rqgEcv7obB1+dTSDheFyNsETvPyAWM/y73c49lh/Bbs9dutRlEABRmd0hinkZT7skFb8kfgwqRwV+tmbCJeBNQ2ls7mGwwZs1tf8mqjJ+iNsWWygrOqzI4KTQdZTGm0STt9NdMmZL/ae6Db2ryruBjJbZLF5CPZ5KENSAeIbQ3RB+waKHCDBbz540pNNpDKX,iv:poHvd4U4dJha27Bqf4hA1pFhna29kO/RnFNjJsflpaA=,tag:/KdR28QZ6ErOMj/MdwOktw==,type:str]
sops:
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMZkpGSzd6TnZ2NUwwMDE3
            cFlseHJ0bFZGM2ZqakNXUGlwQzU3cGRoOGtJCnVzc2xPM09kVXV0R2lWa1RIQXh2
            UWxoL0tCWi9rUVhxeHNSM1pkSklLRWMKLS0tIG96L0wrMm51VU8vV3pzSlJMekZj
            am11Uml5cUlXQVBmZGZjSEU4QlVaR3cKOQEzwUTVFWf8WrpQ3gJZgTpN48NBz02/
            nZ/pJqTB7z85Ta7N7DWpkhPWNYhOBeL6N7vQ8RWvKyKGl2RAaTtFhg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vr0uq6mwv844yvm8pe7qxjxpqrekgel3lqfzuuqtfzj0ehz3hphqzsxjna
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcXF5dlh6NERmR1ZvQ25o
            S2czL3hTNE1MK285a29vOHVxcGhKOTltcUFzClVJZ25ITUU1WHplT1l0YUlwTGty
            VlZOeHpJOStGUG9KcXBIL2hoSUMxRncKLS0tIDM1aGNhUGZCb2pGUVdsZmwwV2do
            c1RUYndOTmFiejhObjhLcmQxZzNxamMKzGso5o0A95HMWb9w4OiUjwX2NUVmniRl
            cnJ2vuO1znJn8e1aeoq3F661NpsLnNqwi3J5xvynfZIcXc2ILrlm5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T07:36:24Z"
    mac: ENC[AES256_GCM,data:Nj3MV5prEYCc7/3NBMoA99YYmWQpE66iM2uIzMc9tdk/i1JQmEUewLYU3lN1WhqE7cqzmpnb4eADISlZ+n1LMoQSZ+btxmbzyvdE2pJaDcYqGyvAOZ5aZR0ycp3e/gn4OJeM+KQqJOWD0Mh1qPXmC/vvXE1Eehpc2iQAZ/70pDw=,iv:ZpW+DXsjwviGgPNPiymFn3wnBsDQNDPyC7FTMzPlr6A=,tag:Jwyqqn3Z6UHjSjay11YdEQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.9.1
