# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "firewire_ohci" "usbhid" "usb_storage" "sd_mod" "sr_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/4a31eb44-990b-4fdd-a19b-6ede2b1ae58b";
      fsType = "ext4";
    };

  filesystems."/nix/store" =
    {
      device = "/dev/disk/by-uuid/1ee9d669-07e1-4f40-93af-71f9ad999f70";
      fsType = "ext4";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/87c5fea1-6bcb-41d4-af9d-b9342a45c9b3"; }];

  nix.maxJobs = lib.mkDefault 1;
}
