# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "sdhci_pci"];
  boot.initrd.kernelModules = ["dm-snapshot"];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  services.lvm.enable = true;
  services.lvm.boot.thin.enable = true;

  fileSystems."/" = {
    device = "/dev/mapper/inner_pool-root_vol";
    fsType = "xfs";
  };

  fileSystems."/home" = {
    device = "/dev/mapper/inner_pool-home_vol";
    fsType = "xfs";
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/inner_pool-nix_vol";
    fsType = "xfs";
  };

  fileSystems."/tmp" = {
    device = "/dev/mapper/inner_pool-tmp_vol";
    fsType = "xfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/5F0D-AEE8";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
