keys:
  - &admin_nobbz age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
  - &host_mimas age10jl78vwyqk622dpn2890l9jl4et3p7lsr8wh8vusem3j8jdxle8qg000qa
  - &host_janus age1swznwyf5zyh66xuex8jnwsargmeq58h8u6fy57ta3xtkgh806ews09ztkl
  - &user_nmelzer_mimas age1w6xjgskpxnlpleswumdhtt7x8zx35qn329yz3x7ftqdcmcxrrvnqnuf9d6
  - &user_nmelzer_janus age18p8x2cxam2l0trtpyhj4x9amcppp9ruzkqxzgapy9wnfpzl9hgaqlkht86
  - &user_nmelzer_enceladeus age1tf0zelmw4lh9gvkl0qycdk83fut9t4q3tfcdzk8cvlyhjp7z0g2q7hklgq
  - &user_nmelzer_phoebe age1vr0uq6mwv844yvm8pe7qxjxpqrekgel3lqfzuuqtfzj0ehz3hphqzsxjna
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin_nobbz
          - *host_mimas
  - path_regex: secrets/mimas/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin_nobbz
          - *host_mimas
  - path_regex: secrets/janus/[^/]+$
    key_groups:
      - age:
          - *admin_nobbz
          - *host_janus
  - path_regex: secrets/mimas/nmelzer/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin_nobbz
          - *user_nmelzer_mimas
  - path_regex: secrets/janus/nmelzer/[^/]+\.yaml$
    key_groups:
      - age:
          - *admin_nobbz
          - *user_nmelzer_janus
  - path_regex: secrets/users/nmelzer/[^/]+$
    key_groups:
      - age:
          - *admin_nobbz
          - *user_nmelzer_janus
          - *user_nmelzer_mimas
          - *user_nmelzer_enceladeus
          - *user_nmelzer_phoebe
