access-tokens: ENC[AES256_GCM,data:bBSGOx1+IyclDJGNF/4NOHaOJAfD9a4BnNfPLS5wXzWh3XXJPAVa4jraVwJ8Jw477Lxi8rkdXVbJiF8GdHPrI9iKJAY=,iv:BPI8HwuKwfzOMT2gs7U0cpbpP77f+X/HvCcfvIJh9Q4=,tag:gnR4sCxNi6neOF4NKA6jBg==,type:str]
ssh: ENC[AES256_GCM,data:7ZLXPWzkzZzTlnLMIUgPHT84wIqcQV0PusW9QemZsd8aODy/mEGfkDG/jENxzSHD0yiMWw==,iv:ENstH9JjeZ2zH6xUb6hqIJqAodKBjFkhHumu5NNEuXE=,tag:wKJIVnw3/Gwd4uGDHjqmtg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkeGFxVWEybFV1dTFFVXZD
            c2RaMW9iR2M2dnhoUG5zRkczckR3Y3piYndzClBGU29RcHNWZ3QzWkpKY2o4cWw4
            MDZrSG9MZVgydG81ZnpDd2VhSldpdzQKLS0tIHR1RWQzZWZGR0xkV2lDVVMzLzl2
            cmg0Ulg2aVBpakRPNVc5SDh3aHY3OFkKYAVNdjtpfSvgYuEd/Mz1hjHmSfZf37y+
            Lnh2gfEFSTKEr42EtZ/aD2gjeT5CgjnRSkaKXRINM3L/6G0Kyq3LTA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZ2FqQjlvckpmSTl3UE9x
            TkxuNERRVjZacHI0SllPQWJEUU8xa3F0Nm5jCnI0dnovcDhlRllKaW5QTFNvblA2
            b1hpcy9GVUY4YWlXeFRCekJ2RzVNb0EKLS0tIDJPM09sTVZGYm5RVXZ3SS9WcGl5
            L3ZieVV0RWM2bEhHS2xTSkNTM3lhR2MKre3b6CaXZQkB1eodh8G9Enui3/XC9sbG
            5RBRcxWBwMA7CcoSgzjIQogWbhjkQwv+zMxibG97gknHzysQlbO5FA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1w6xjgskpxnlpleswumdhtt7x8zx35qn329yz3x7ftqdcmcxrrvnqnuf9d6
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQVnhSQmNHbThLQ0NFMlpU
            Z3B5blFGYWkrY2ZjMlptK2JYUUNiYTBydzNFCk5SY055RVhjNDZETTVZOFpBSXFt
            ekRuVS9QejJ2blUzcFZVeThBaG5JTFEKLS0tIEJzb1lZN2dNU0hRQjJDWUloRkZQ
            NnlselJzcnhScmFpSE00UW9HMjJETUkK3rx9tlYeRAXHYJs2kyl68y3Is2t3GRWv
            AMcjFLmvdIwL2e6oRJemvxv/06vEFTAx+9K0Ykt7F/sD5rJ6zc7xGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vr0uq6mwv844yvm8pe7qxjxpqrekgel3lqfzuuqtfzj0ehz3hphqzsxjna
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOS2xHS2VCcHdWbHNtWXVY
            UGxLZGxldnpXQkdiNENBOFRHSGdObTlIdlRBCjBHelNIYU8yZnl4Y2g5UzRJTGd3
            RVZSMXVrS2VaYVFQekVodGN2TElNdEEKLS0tIGZUc3g3dFgvRkFDMkFWS2V3bWI0
            S0lhaFp0ajdVdGlXcVhlck1XSUhmZEEKkjAI4rRH+cDIPiuk5228quvK7OIt50Aw
            2Kdz+hRFDWN+6bHbiBX73W9hBy2Uz78sGK7QYtQaAXIJqcHBzn7/Nw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ct3c6gkyj80jexly8a4wazs82emxsr5pq77m749udp05eaj6cdzqfgd25r
    lastmodified: "2026-07-24T11:44:13Z"
    mac: ENC[AES256_GCM,data:EFXRfCZpT3Rp8fHbGFSz166/aCL/hiK0gM+dn3cw4wKtqy46s6+cnGaIQzSF04JeHm6zl7dxM9SoFbcpBoAOJCWhlg/sC5OyQhp7+F1DNZWJVZeySECVD26lvPb6CWuobQf7UohBQK5Y3XQ4bltsbo5mG+ZF16AHcOYWPSCxRso=,iv:QL/fAfh6qqrkPuJhmSRmkNHTnPsKEV9q2m3hgYEWsbs=,tag:ySNzBPDiUMd5O2kJd0jYww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
