restic: ENC[AES256_GCM,data:8KlD4QjLle1Thw==,iv:9NdaTuhLR57mv8OaCSyso9cfr8V1iQNuQuWInKyi3bI=,tag:hqoLmZ5a1aoNfUW58ufrpw==,type:str]
traefik: ENC[AES256_GCM,data:I37mOlAhhxXG3XsQML/Q5Bxy5LSOSUg4pG4pcmyXm+F5iOlxDMVhZLnSYaDwKaN0cbV3/+SwpuUpOM3XfxpFMHCioN1uRJSx8GufUDigiuQ+IQ==,iv:ZL90s3YuBmwafBz7VEwCTr2flnkguUxJgPp9OrnyfGA=,tag:BOrp1FfrX6xyzqUMOPh9qw==,type:str]
warden: ENC[AES256_GCM,data:nuFBqVHvRwbYLYB07T6rrd0iQy8EhT5NNkLuz+k5OHvuxQ5dT/ZPhLKP7JXG5fF984RiCe6Hc46uhNrrH4NkfnvxsUVRy9uwMpZ1JrNqI9zT7srpCMYD8z8E42IhGbYVL5ylt7DEel8KAS+TqvLoTbzhKe7m1PIw4BF0yg7OEKxLz+kT56HYAmPhKDRR2WTMxwfkUUWln7Xs3T7Ax1FCZjacfS678R9xYPDuCXkx/l+z0HIG+GBpl/+Qu2PaS7SrHFovU3h5MEOahFXB313FoeReLA/vuQqSkncD7QmceEi/FK4LdiqFgM/lR/3LejpnwDD8q3FMwtiluUY=,iv:OauSp63ywmrkENIqBVGVQ99Ozyom0o+DfSqYaL46Ujg=,tag:sF8LwNMBEg86h8Lhjmj0AA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrb2tiOURyVjZicm1CVEUw
            bmdFb21oYlkxNkNadE5ZeG1ZZkhZTEYvT0E4Ck9nNXg4MUkrRmRlakhCVkVWVVFY
            RTRRcllqbnRTNWdRcDZqdUNKZTZsNTgKLS0tIFFydkovaVVkRW9ZTnFoYzRSSXRL
            eDRHNzNHZ3Q1RlRta05UNVNRSmRUMTAK0O4T16WOKrjO9Bsb/EHe7i+phUbD97N6
            t8WSLEiQGf2soA0XZWTMDiMPNA/Upyr4XDYwQJD/dmtedjVteGhyNQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jl78vwyqk622dpn2890l9jl4et3p7lsr8wh8vusem3j8jdxle8qg000qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZ2x6a042SWduUUMvMEVl
            Z3d4ZXAvNlBhRXJJeENwNXExVzkzOXFPdzJ3CnU4SkhhMnc0Qy9rTlJWdHFKb3RH
            ZUVpaTYyNjN4WVp4VldKZnV3YlFnWE0KLS0tIHhuTkpQTUo1aGttMWpMSmE4dHpm
            S0s1UVcycStDQzJ5SXR1SGQrYXdYOW8KWRFq9NaW/qL2j5DuPfmGTWv2+fZQjGAS
            ySDUFmHz1SLLDJK7q8Zc15YSuAcK6nverSRl4Z51XRWr1TSIEYevFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-25T09:55:31Z"
    mac: ENC[AES256_GCM,data:z6+BhdMoGK9T1/clSu4s0oUN9O1jCtAG2kFhdXA7CeiKhbkigeW00wAx5X33v0+8enZGNjuY2d7hIk460bMlTRRoeJ/ZqVhG5Wjslccn4y6NIBjpCW1/G+pCC5qz4mwCPgt24I4U+NrAJVCgcQiXHD6BWTXQeG1QxNm68x/rlJM=,iv:lqyxhTAb0RmKKlXDSC2RWKs9f8P0sFqQbGoEIvgky9Y=,tag:ORDLjLB9V8amR0h5LOcjcQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
