restic: ENC[AES256_GCM,data:+kRL9guWwg+6oA==,iv:9NdaTuhLR57mv8OaCSyso9cfr8V1iQNuQuWInKyi3bI=,tag:6O/Mt6WUCTLiFzwCj15VaA==,type:str]
traefik: ENC[AES256_GCM,data:1sdVmJiGYIhi/IhTZXoT6PZ3PHU3t/8zyF37SoKipyM63djru3jJbdAJJxhHjJODQKnA8rIYwkIcEOrINbliITQJNRKS31Jd/2dWNZy5JBrD8Q==,iv:ZL90s3YuBmwafBz7VEwCTr2flnkguUxJgPp9OrnyfGA=,tag:T2/3MRNgR3e0jyVQ3wha0g==,type:str]
warden: ENC[AES256_GCM,data:GR/VvznubhzDX4usna4cN870BnWIECnXkRWzcyLLQRXWxCi0mVqL/OnXU682Exdv0vl+1sp4rR/O9XieZbcYjYYggNJmhwYXdTHbgaIgD1opSjewHzGfSrgTIz9xa8Q3wO0BTbOXRL2jY8cFYAnHECjCfzS/ZqEsT2PbS3jsxYQxIpcrUbq3O4TdVfkVuR9zLdgvCIbMFVPMihwE3LFATkjrpAOG1T9sV9vT0CDNysp7M0msA7OqytXwz0zMmIQtvzatlEtqG1Jm1RnPratT/sFV1YX2FCbBUp5fTnvXET1rLvx7sQUQ62IJujWYuS1tKdR3qPWVVslo3pA=,iv:OauSp63ywmrkENIqBVGVQ99Ozyom0o+DfSqYaL46Ujg=,tag:HVvSCI82uZggDuToEsv0og==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTTJtSVBBQ1BCa3A2UTZ3
            N2NmSWUxVUE3bklCQzBqSi9SN2VjSW8zTUFVCmRLMmpYazBtR0hFSnRWNEk3THBN
            SklxWDNBN3BMNXpxSnJKcXpIdEZNRlUKLS0tIE9IRElWOFBVZ0lvVHlNQ3V6bENJ
            eWhNYWh2cE9DdDR4d0NlaUJjVGJaclkKdEvGO1B1QDDrinGBtSB7jBCfcu6Y8bG6
            USucRBL/FhiwjBc2Wr8EmFkrEJ6IYwirOBax8uwidkecEK/jdqF0tQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jl78vwyqk622dpn2890l9jl4et3p7lsr8wh8vusem3j8jdxle8qg000qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMmhHcFJ1dy9zQy94a3dB
            aWJIWm83UEkzSmZNalM5aXEreDZQZ2lDdlJrClBPT2xyQmpIZXp3ajhsaERRUW5u
            YUZvTERWS0NFZEcrQzJQQlllb29NVlkKLS0tIE9LQUdoTUpHdWNlbFloOWdGblNz
            YitpRmlSNjY3SmNzeVFmRXg0KzJZbGMKKPR4KSO4LhofY0JOfqBYhb0sLqJyD2Ui
            yKn/1aNyYKKkTUdrSIJN5DQ4i3D1TQTNz1MJ0sD/lAOldytXz5lIpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-13T06:10:33Z"
    mac: ENC[AES256_GCM,data:7O667JUoFb77x9xx3/LeELrWX4Ip8ChNZt5+pl00mS8sU2CfCuCwo2PEAskGkqFpFQFBvEOCl5+XUIavfKHSTwQR/k1MrMYO9jOWpU8Mr76ESmS26b68p2b/EwIw6S+WIYX9wKBiMuYEtGmZvdvn8DIfYWRt2tEdgWe4EvxRwec=,iv:ChKdLpnyEwCsZsMI2o648fdYfjqMPkigLDi0WrgmCRM=,tag:7bG5Yu28Nr9qM7cufJagQw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
