restic: ENC[AES256_GCM,data:dHf1ywXOK35QWw==,iv:9NdaTuhLR57mv8OaCSyso9cfr8V1iQNuQuWInKyi3bI=,tag:kgje5QozmdkTdPgrWHU4uA==,type:str]
rustic: ENC[AES256_GCM,data:550g4xfP4jXTDiM=,iv:MXlQuvTJa2mZuXeiCX/YYpbqKpT1+RE5TNahBrUMM3Y=,tag:f04TZSQeZbqoki5qg8pGYw==,type:str]
rustic-user: ENC[AES256_GCM,data:0wfKCyKx5Q==,iv:y0pbF5axrPRdYRGAmx+kp7jkmSl77R8LQMUKQaiDWak=,tag:/AorC2vA8qCDXiECrzkAKQ==,type:str]
traefik: ENC[AES256_GCM,data:oZybVFjhBIdxQDzf6wBEEsYxrQXXFwS2ZNDuuYzeHr2dpk8BuuAdpxMdaRSyvjFcX8inBkvpPZGE+/kxe86XpspwdmHVaWT9owWSl3kxojozYg==,iv:ZL90s3YuBmwafBz7VEwCTr2flnkguUxJgPp9OrnyfGA=,tag:snfM2505kmdt7l/NVNwS/Q==,type:str]
warden: ENC[AES256_GCM,data:H2JYJtSdWZLNBlzFuKNPlKirr6KHeqaCJSNiUnhD9puVWeZJ7wsXEtY+Lw7sL0K+5gYF5QaWb31PuAPsRL6md5TjcPirrUCoZJh0cjzAmhIaW+JJqXaShDWTVuG10GhlOof/w5OGRqmB7pD0b1Gr7nE9eGsuGYcv51UwJmu6qC6MML5CCyqC5jpOforX7epjtEo7YDaEkoX/G0tFw0jQv1XE4XJyullvs1T760+JE69eAoKZszWqc5iSTFEsAgE/JsLz3TNQRAVZQ9fgsveofJuKj423g0GIvlsD1ZUqLc6LZlRXK06MlnxbYT8D+o85QaElta5zpErWCfM=,iv:OauSp63ywmrkENIqBVGVQ99Ozyom0o+DfSqYaL46Ujg=,tag:iW/XGDNNfoO6dXuUmoFDsQ==,type:str]
searx: ENC[AES256_GCM,data:0XFK+Tex9jmKng2CSFJmlYKmcA1hSIg4w/u+k9WeN1p5BYVl/EX63yHe5EgCauiGfFro24UXzXAtzFptnIij3HtO6T+6EkitHbdsMnH+L7U=,iv:TjSbP5Ej7RMzrZWNgrAwRsmeqOTzr7yOuvlcabSBXWI=,tag:Y3+v4OB1HQcBWsWRddPocA==,type:str]
sops:
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbHpOSXB6SkZJVEdWdTgv
            eittQkQ5dWFsejFJSmhrSmc5cVNvc2VLOFVnCkx4RGpZNDlqZjY4S2JXUE11QzVK
            N2hVRVkxMFBVNnNPL3ZTVnhnQW9qNVUKLS0tIGdZd3VTSCtGeWM3YUNEU296TlFF
            WnVLdjd0bWVzM3ZhUVZkL0pISjZuQWMKQ9VbobmZO9vu7JIUpaxQMyWRcBC/Mvo4
            FLRXet420YpE9pS2hHqZKzHG6Kcee6fXv2x4LahsDYSwnyq5kLAVxg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jl78vwyqk622dpn2890l9jl4et3p7lsr8wh8vusem3j8jdxle8qg000qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWGF3VVQ5cll3UXZLeHBr
            SkRZbG9QRzlUd2xxbVpCVnk1eWJreHI1MWxrCmFmd2N0c0h2eGEvUkphcEFxM21t
            emxEelJLczZUU0Z5R2I0RDFkbXNnak0KLS0tIFZUZk9iLzZnNkJNVzB5Qzd0akZP
            cnRoVnZTVlpqSlRPcFgxVlRpRTMwVE0KNfO/MjYYtLjU4o+McMnrbOjySlZ4eqt2
            NGdJRsnqn9wpXHBBX0xH1dymmrE9bQqb7pOZYcueeViHJeiwGb3ISQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T07:36:24Z"
    mac: ENC[AES256_GCM,data:4OAjfuTZ4umJ8giBROMUb8/amQZiBeXB2eOFUxxsYYgfHpLSBBybceH4x9ZjYHmR+CJSvb8/8sG3X4EVBJJyoN0xL5hnMWyVKx3o1fYlSLKQQGY+6uoeF0jJqeJci/Z5fzCm/QNq1022yNy169Ha4rSb8TOgEsJSuWSgUmnwYAA=,iv:F5yrpwPVhClHPwesKPdU7oRgXpSCIuS9Gd/lw/SZBYY=,tag:VdwGHXHV2IIvtAfozkpfQQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
