restic: ENC[AES256_GCM,data:CoCgNPIOSG6UXw==,iv:9NdaTuhLR57mv8OaCSyso9cfr8V1iQNuQuWInKyi3bI=,tag:qYB3FWJlg6IZlj+hzI80Jw==,type:str]
traefik: ENC[AES256_GCM,data:Z8KLXUR/upNTLvldlDwVHTPPajxqnAORUNYXsS73DJo78kpIwbWgrKtPiHWWCM4Jqq1qaFxiAyupg55Tatv1zJ3UKoBHDDi4sKIAuRy1Krwz3w==,iv:ZL90s3YuBmwafBz7VEwCTr2flnkguUxJgPp9OrnyfGA=,tag:1SBN3KV0agQB5F6H3E4WnQ==,type:str]
warden: ENC[AES256_GCM,data:KA/BDwMCdCJ9fWZ1PVcAOnejoqNYjY9LN6xh+O4bqlZFCj3MY02EqKfLucEbyhyCIJDWm3NC44ZAdfSrhlauabAI4T0XKHbDdimf5To3ePK4N3Pz4P+Xs+Te5gfeIZN1sGpE7QsTqZD6/Ludpm/4RureWRfhvTlVIrr2TBped2r/YbcNH8RXlETvzunpGVMNtSWd7kfy/PnoJ3Ug0X17D+RiVHDXG3s9LgfwQq19K0w3fIHDRwXLPwxQQUEGf/K9FIl9XHidOmSpiYHGohfSEn8dw86FPKjxfhdK/uywXPXRCieTzc6xB/9jy4ko6zyP6Xp7+NiKDNWy7H4=,iv:OauSp63ywmrkENIqBVGVQ99Ozyom0o+DfSqYaL46Ujg=,tag:4FAwJDzTWhFBqFxooo3t+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQXZTRjF0b0pIK1JxZUFt
            NHlPZzFUR0VTL1dUQTVPRXNESUJoRkw3MEc0Ci9qUjc2SmE2d3R1ckdBWjF4Q3RV
            UEtDSGI3VGVGNlJNc0xsU3BBVVZhM3MKLS0tIEtmODNrVGpDaEJ2K0ZyRk1GT08z
            ajFTR1NUSlc1NC9HVDlZWDM2MzdiTDgKOmYAKA/bOgAesezmYUHH+ZR/BFMyUqzp
            q3ORVxE8DAiPtc6MSREnO8saNKNMv18qVVY0SKPCyhWFYg4sLbnEng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jl78vwyqk622dpn2890l9jl4et3p7lsr8wh8vusem3j8jdxle8qg000qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndStma1NtRzN4VWFSR0N1
            dlBGT2lrZkxzandzT2RBa3R4QmZNRkl1NTFFCkhNOGhsZjFhWmpLS2tzQWs0TC85
            cVhXQ1lrN05OalJRL29OenZaOHcyWUUKLS0tIG9FcVF0NzZERnV4V0pYM3VNVTJJ
            N2FoNkFKRDhZUE8xa29LVmJnTjUwUkUK+IiaSZycxZgl5GHoFom2Fs92gBQQZ/QO
            DepPksFFqqG9YW7V6c16ejMc7SNtt0szQwbmqoTviIadiv26+XS8Cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T08:15:23Z"
    mac: ENC[AES256_GCM,data:9NdDIKSD9sKV4D8cdM0/Tl5K/oJCwXrdJjzolw6w/IhxKbDjZg+WJXAj5WWML9YPfFZkcof6Q4uo+hfKhh0YgFhf32pfZxk5Pm/6+d3EKs10dTzkgPvE/VlE99edbchT6U4ORCikpakWI1lGhjm4PTUlCrdFh0siv5o6svyvF0o=,iv:hIRKkarTlSpVLqUA4UV4O052YEVkjS6LPA3NJM4rQGs=,tag:adfiMS8+8mJeic7KhmInTA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
