restic: ENC[AES256_GCM,data:CoCgNPIOSG6UXw==,iv:9NdaTuhLR57mv8OaCSyso9cfr8V1iQNuQuWInKyi3bI=,tag:qYB3FWJlg6IZlj+hzI80Jw==,type:str]
backblaze: ENC[AES256_GCM,data:GGTO5yNe9zVFY9itFxSzcKBeaG3cler8hrVnrLnktdLnOkgUCp9JUpAYOLeQiAH/5xwBPuMabQULXr7y3a5RbbmcXpgrKf7KKOzV3TDMwVWCan4/c0dzu/w48B83PuZw/Fg6uIg=,iv:kGHjUYWYpY5XBVr9EpPMwxaEsFFBwn+aMgmHScK9quo=,tag:tJyw6851kSGcOB14d3BKkg==,type:str]
photoprismAdmin: ENC[AES256_GCM,data:/MYWdbmA/6sUtg==,iv:jCaIZLYUCFj9XLr35KiUJFMfyfmGfF/rgoJ4aHb67Ok=,tag:2HwQc+N96yyFXEhJaHsQAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQXZTRjF0b0pIK1JxZUFt
            NHlPZzFUR0VTL1dUQTVPRXNESUJoRkw3MEc0Ci9qUjc2SmE2d3R1ckdBWjF4Q3RV
            UEtDSGI3VGVGNlJNc0xsU3BBVVZhM3MKLS0tIEtmODNrVGpDaEJ2K0ZyRk1GT08z
            ajFTR1NUSlc1NC9HVDlZWDM2MzdiTDgKOmYAKA/bOgAesezmYUHH+ZR/BFMyUqzp
            q3ORVxE8DAiPtc6MSREnO8saNKNMv18qVVY0SKPCyhWFYg4sLbnEng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jl78vwyqk622dpn2890l9jl4et3p7lsr8wh8vusem3j8jdxle8qg000qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndStma1NtRzN4VWFSR0N1
            dlBGT2lrZkxzandzT2RBa3R4QmZNRkl1NTFFCkhNOGhsZjFhWmpLS2tzQWs0TC85
            cVhXQ1lrN05OalJRL29OenZaOHcyWUUKLS0tIG9FcVF0NzZERnV4V0pYM3VNVTJJ
            N2FoNkFKRDhZUE8xa29LVmJnTjUwUkUK+IiaSZycxZgl5GHoFom2Fs92gBQQZ/QO
            DepPksFFqqG9YW7V6c16ejMc7SNtt0szQwbmqoTviIadiv26+XS8Cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-30T19:00:14Z"
    mac: ENC[AES256_GCM,data:bQ4qc2Bi4kfRFLL4yHx0RV41vvpAyVdnqQhWhvfRpsUKFG5RruboZCrmUPeovyuPJBmXylO4Utj/T5tldtoreYuhTSQ7vhzCNz9EivnLNbGz/be1g28cWXisHV3X72AsKfugz1QyrWGQkByLZstZKKteb5PjZVxp2O4ZmG7KwGM=,iv:taLvrbJpBBsazhuJ6f08AF1dVUe1DqYO4mkDLZntA+I=,tag:XAsxaxFeSkkxhA6S2Jo2cQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
