restic: ENC[AES256_GCM,data:CXfk6BpRUYburQ==,iv:9NdaTuhLR57mv8OaCSyso9cfr8V1iQNuQuWInKyi3bI=,tag:xtHD8O8V0Z/Jwqn76emrlg==,type:str]
rustic: ENC[AES256_GCM,data:ZPrffyee9/7dnzc=,iv:MXlQuvTJa2mZuXeiCX/YYpbqKpT1+RE5TNahBrUMM3Y=,tag:ePwKAkwFl8OzmVpXWK2dQg==,type:str]
rustic-user: ENC[AES256_GCM,data:tEeOHJNw5g==,iv:y0pbF5axrPRdYRGAmx+kp7jkmSl77R8LQMUKQaiDWak=,tag:YYGGU7x4Dt4j6rXVnFiTXA==,type:str]
traefik: ENC[AES256_GCM,data:wYn2T4pBhsER/yiUT9H6UXIG7GNfAliV6JsFfHoSJWeKOxpi/EKrFygRrS94tbQ2EDat1cWL/8tUEWbt5xCnv3h0dcA2KvanaIDnvGxkT8HKJg==,iv:ZL90s3YuBmwafBz7VEwCTr2flnkguUxJgPp9OrnyfGA=,tag:cTexWMtVehF7FkXwoLVIDA==,type:str]
warden: ENC[AES256_GCM,data:LKYvZXYk37WwoRNWKrdoKO8SiZxEBg0pv2BSQjAbtbnUz/y7AsSXNYAqwJEujmckeIWHm/WFbk0LymsNlnGM536uuQNoa0U22Xqd0EhOoZlo1mZJ4cCVPrM1gthV4ipFolxjZVSwEjhEUMUKD85odNcxHd8HELQd3+qjkZkKpyMlG/0i0zYmnTWF/AJc42GfC7lPCp0D82ea3Yn4qdak4rQQsjXxXEwUYEuoGBkVngcDdBTpkK7qawS5ircQOMoggJmmQh909prwcNyAvI088ndLEKCrE87cIaM0iiDaEjWqUDxMxLWy16UFZC7LD4Fu2AxXoj8yggKwj/U=,iv:OauSp63ywmrkENIqBVGVQ99Ozyom0o+DfSqYaL46Ujg=,tag:VnnJw/cEMn4xW5Oel7EHIA==,type:str]
searx: ENC[AES256_GCM,data:JvOG4BjXcotaCeZjy3f3iOxkasz78THJSJjGWklcAV7fILPXKKZ2uHmNBXe/LOp3I95t9C/9pjgsZa3bbEnIuqEoPeB0teaGersycHN+dsE=,iv:TjSbP5Ej7RMzrZWNgrAwRsmeqOTzr7yOuvlcabSBXWI=,tag:YPknqoPhq8DV+uhSAIEoSg==,type:str]
sops:
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3QVoxa3pWMjJXeE1JQXAx
            UXNQRDZqdFcvZGl6ZEJCSWthUFlXK0xxR0dNCm9lVjZFYUhtQ1NIbERZVUIvV2VM
            YXB4VWtaL1E3WU9lWldXRGtQalBTM0UKLS0tIEpxOFJyekg5anVVem1ka2wzZHlm
            bEUxTFZGcW05VHYxT1p1ZWh6cTFkWTgKEJBdHP9wDwpmQO5HRWGx7CuQgSWnwsA/
            OsA6wmUE+lT2uaA6fK7IP6y+gAGT5VNpFpmhHPI7XY0xlw6NOZ3Dqw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jl78vwyqk622dpn2890l9jl4et3p7lsr8wh8vusem3j8jdxle8qg000qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNFhNTHIzK0lxb09KMjhB
            TVNTQ09PMlFZWkQvOGpaQm5tbVA0R3V6UUFNCmFtOVp0R1ZTRUlvbEIvWEJVUmZa
            blpQZ281SWc4dk54d1Y5cDNXQVBacUEKLS0tIElsd1BveGF5T09VSGUvYm1qazAr
            OEhFTkxDUFpJYnluclJRS29sVG1SWUUKH5veb8if1H+kaKx13VkqHx57jt07gDun
            30I1hFIe2avR4BxPo/x28esX+6Vt5OWfo/iiL5f7JPg26hCbIFBIkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-02T22:56:23Z"
    mac: ENC[AES256_GCM,data:V1Wqs6dtsvaqfUUZ3lDzhUv5hKFZd4ssX1YakMwiF9HnRxTk3hm5HcD4jj1VFZ19NcgcXAAvC/wwnf8QB3UeXo1lL7VNd0Icx72lsEdAPttxoE3/T0wdeMg3ijv1qtr+Mlex/Q0UmYj/Djw5GbtgLu3BFXM2Oj+7PINbAA4W5xQ=,iv:4GRdKu6sJj+Fwd1tffXGMKz8qTZv9Ts7MVJdwS9L354=,tag:UcDAGVd4qyQdoxmAcip3Pg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
