restic: ENC[AES256_GCM,data:RalEtjybp8zatg==,iv:9NdaTuhLR57mv8OaCSyso9cfr8V1iQNuQuWInKyi3bI=,tag:7JqSaYtGIjScuB/T1WzvuA==,type:str]
traefik: ENC[AES256_GCM,data:YY4zAJ5FEeW2/We+BgO7G7AJmqTvO+cAnlq1hBdXgtzpXhm9viv8WIjbUAPGOzsBk8qgWMgZ1azECUWoFJWNRRFVrDNRxzM2GkGK5RoM6nUY+A==,iv:ZL90s3YuBmwafBz7VEwCTr2flnkguUxJgPp9OrnyfGA=,tag:JkMJsFeEk/UKbdyL/VTBhw==,type:str]
warden: ENC[AES256_GCM,data:/vG+a9TP18S8jYy1/ZoXFjbYYpa83HoHC5VSHaAHzkzGSYD8jTq3PyKQke0EwfO6STd0BU1MUGYhq60uGQO/anOXiW4T8j42a+7Vf5PLQ4kMHHTn57fG3UaWILg8dOE7cpRgKaLNsWwYZqgngP56w4265LPm9I2o9UYDYuNn8qTt/TSHKba31NWEbBjIDxbY7fW0EXzqOG+5RP1BgQeoQYNhiRB/45VZ5zOTsq4RWHJdhpKnkpO8ory0ONIqnBSQk5x2zRO99ys2renWRCkRQeJlWTsLfY/zd9NucrzajTT4jJfoe523oYtEAaRY2zGbI59hkrqMBThIVfU=,iv:OauSp63ywmrkENIqBVGVQ99Ozyom0o+DfSqYaL46Ujg=,tag:I1WMIXLHPZCActYPqSJY3w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbEMwUDc1ODlPRWtDOEFr
            MVRpSkFhTHVudk5zVm12a0llWUpuR2poWUh3Ck5yUDBINUZNV1VQNXdRbkx4MjJr
            UjUzQzBEVjVHS1FvT1BaVDlQb1ZzaTQKLS0tIGN1RndkUXZnQy91UXVzdkRpaUNH
            RHMySGZkS2M0YkZTaFBDclpxYW43azgKl75qDMpRi8XSghFaiHKzXhkhaHcTfB/4
            tXxlqpLNalHd0i/iDirFUwtGr3k4544gZ/yVgE77P9SX1jA7kYJXJw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jl78vwyqk622dpn2890l9jl4et3p7lsr8wh8vusem3j8jdxle8qg000qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Q2ZJREVJdlFuVmY5T0JL
            WGVFaW4zYkc5aWxIRk96UDEyTVZ4ZU1QaWp3CjA0V3RCWTZVU0ROL0lTUExXbEdF
            U3R1WUNkZ29vU3FtcU1TaVpJWE5MZGMKLS0tIDVNekFEQUR4eEdTWGU1ZmUwb3Nu
            UXN2L2RmZjZUcEtIeC9jbzFHMXlUR00K1A+9Sys/oH8FDcY8KUKY8BjcNv9l+3OK
            c/GmQCNaz6uUf/SWfSM1E/RhTHus3DEYD6fWZdzKwEzsYs2ZPRI5Xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-12T10:24:40Z"
    mac: ENC[AES256_GCM,data:lJO5gsg9NTWxdbS0XbamH3rcFHHUTthRmdJ4eqXGX/g1bsQcFwoSVy3FLXkN/NQkaNpbjdoqWwRkvUlwhuvDhjCrMERvEUFCEivSvWVZkl6TqA1soMFsO1FngaUvaCijlMbxdE94ZLVu9QRe5Q0sY7qL7EthUvC+ykXiBwvzbEk=,iv:vGv2nhSfBn3nxv+BbxkAb//m9Q4Ycn67a1Fz9sfTptA=,tag:BjB9IP0U30473t80FffeZw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
