restic: ENC[AES256_GCM,data:Dmp407bja+72ng==,iv:9NdaTuhLR57mv8OaCSyso9cfr8V1iQNuQuWInKyi3bI=,tag:ZJxncSj4IK/F/gqewdSvHg==,type:str]
traefik: ENC[AES256_GCM,data:7oog8NJbBf507iv5Y7qT/A+7LPmtYEnZE/mCDgB6XWAWlic8D17Iys11nYuSzW6cCU2afKeubl/UV0xJuBvyFj+YRoEO61BIZ/aryvlKtgqIGg==,iv:ZL90s3YuBmwafBz7VEwCTr2flnkguUxJgPp9OrnyfGA=,tag:RuwbtKNkrvKqb2cnR+2H3A==,type:str]
warden: ENC[AES256_GCM,data:j0KffGb5zzbBgbip26XUnJaI871OE4xxUtUC4ebWFSiu8i1yAJdnx/xVZG++SK8h30HBqiUqy1vdfRxxTK4ttNI5uaG2HDq/G3+EQNVL0QzahAMIHs93YaExfD+A9iLvwHZ9LEHUhyx5WTrV72fdzYIjR3RR5e9yf8WRDFj23/WaJXGv7WFvgylXTvw0CvN230uYcwIflEM1YdlmmcpgI2udYuNoR8dNU0OGaUGVrDSVwZz4uS7ylInVK3hJ2CBXCLGXU5ql05xSjP6PPyYj0VL7rnEuVdBC93i+oxLlDLo2l/RvRQnSlmHlYrDvaF7lbIdEBZp2HbducqI=,iv:OauSp63ywmrkENIqBVGVQ99Ozyom0o+DfSqYaL46Ujg=,tag:S+ABsW2KXgWQHoJj1ALrqw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYWp5ajF1LzNKaCtlaVNm
            aTFndDh0TEpPcjQvemdCd3lpY1FlN2g5dlNFCmdUSk1xbWlCQzRDTHRRbFpRU0JZ
            NnphcXZRa2NnUWd1N2E5dUhHU1ZGSjAKLS0tIGltTlRzWWJLTjJTSVVxSnR1Y1RU
            MjRONXR4WVg2M3JaZnRzUDl2cVdzK1EKD1EPzYRyHiTo+RHri2OAlVStFPG4fROJ
            bKSqnuCLioOFSKL3zR5oZGcx2fb57TaSv313aTEn1Ugmvmodz4uEqg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jl78vwyqk622dpn2890l9jl4et3p7lsr8wh8vusem3j8jdxle8qg000qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSVdqWFIyNFI1bWJMdHZI
            UTZzUDBpZHV6b2hwVU5XaThnYVlzaGdnREc0ClZnYU1pd3FiSEc1bkU2c1FkTFh0
            K1N5ZGFTS2dzd3dkaHNTelpUaDZDMG8KLS0tIFBtQ1h6eGFNQWJ5YkdTeUNTSlNj
            MS96MWpNR0xYS1piSDZSdWZkdFVQSGMKU1i+xIrkArmYRjNd55S0W+MAdswJfjXY
            QQXectLU68BaZ2PDukzMUxR8SUPJ8kNSAb2Cokpe8AhNAmnCmTN2cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-10T15:44:42Z"
    mac: ENC[AES256_GCM,data:bgj7qaziVvEfLqQZeAFpvCASz5Xch7AIlatcD0zNQ86p2KEgDGO6k0aByGrQ8ENgWWBkPidCZUSkw6sO9Qyf3ySoYEdf7C9AexX6uKayWv3PUMOrJoJghPA32U7oxBtVzyDxzzD4bAi1rnUTUcQZuUixnPAZ0edSKlsrhH4HHvo=,iv:lFrDbsV2MhYVoJ3SxHS60uVJnr7EELRLOn24tBRAOek=,tag:+xTaEF41iMj4KLC3sFb9xw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
