restic: ENC[AES256_GCM,data:OGkjGd5uZHY25A==,iv:9NdaTuhLR57mv8OaCSyso9cfr8V1iQNuQuWInKyi3bI=,tag:TUVpcJlEk70gRTMSRFcUoA==,type:str]
rustic: ENC[AES256_GCM,data:+OkDEF8smUKkJ/o=,iv:MXlQuvTJa2mZuXeiCX/YYpbqKpT1+RE5TNahBrUMM3Y=,tag:r/BQw3+72pWox1MUmfYl7w==,type:str]
rustic-user: ENC[AES256_GCM,data:AGTU+OpOhw==,iv:y0pbF5axrPRdYRGAmx+kp7jkmSl77R8LQMUKQaiDWak=,tag:hiSK7UQh/z0ZlDX8crjpfA==,type:str]
traefik: ENC[AES256_GCM,data:i1L6zpmXfsFUyjkiTGdeXw73zEBXz00V2brZHyghHitUlXALfU/zfD8+1zuyvYy7Pqu2PH8iJE7tMza7mgSBIWsvaKcJXjV8IYLC01ryu3aj3Q==,iv:ZL90s3YuBmwafBz7VEwCTr2flnkguUxJgPp9OrnyfGA=,tag:qVcaJ+LhtCgKIbY46vfSDw==,type:str]
warden: ENC[AES256_GCM,data:3B67rmBIxcimQM1PBGRQVhznFiAcTCFrwUhmRp8ET/eig3Pv9YGOGU+2PzlE64oEwm1nFPuHB/8qfJIOYAPmtfAt7Wk25drsbvbcQJ/mBl9QMp1nxpnAfBqS4Y+na4jAyGoq4k/5O3c27MVrlEuKYnDNZ6MBzqTQMwlEoBbUsHVk47KOelyPKk68xFng1sa/2ZwIo5nkha+xdcqrRuVbIYyWPorvGLHl2nQSS2mVDdd9dDvWIj91yvaWkjc5bUZ5mTYzrmUw6ac1EaxcBMpOktYuz3kjVml0VwbmIpuaswr3GknzpnzU9r7QO+M62J64dCSOWSxYH2uOuLU=,iv:OauSp63ywmrkENIqBVGVQ99Ozyom0o+DfSqYaL46Ujg=,tag:WA2YG7R7SoMRNfn6vZ1g8w==,type:str]
searx: ENC[AES256_GCM,data:KuxH5d7UFYeYvMcpAjy7jlqLS/Ii9CNR0zt3lPF/g+775MEZsSGyDqNEgFrQ9QKbN8YEsVzUocDSGUXl3ppnCoaShiNP80oqSo5iaz6DRrk=,iv:TjSbP5Ej7RMzrZWNgrAwRsmeqOTzr7yOuvlcabSBXWI=,tag:rqHAeBsjnoO3WqZMZNcbbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVmpYZjE4eHlLdzAydFRK
            ajZ0bHM2YU9mbWIxSzlCdjVlSHhYR1lJY0FNCjZYVCs3VndUbTZaZGVmRXhSQSs1
            cE96YWhXUWVNcmlHSVFrMmN3VHFpZWcKLS0tIFlEN1hmRjhtUlpSTndaL2tKR1BE
            ZjBsVWZwL2djUCtLTElpMGlreC9VUUUKtW7FirFaYznJzHuRuiqWqPSLl6nW/krA
            UHzBcSYOgXzqSGm5A7uF7f7JSGihKTVjKYkuwB7XaGRFeU/EjHZFXA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJMjBFd25haTBIV01hb3hk
            TlBXeitONGVDd3UvR2VtWnZZSVVncFNydTFNCnRLRHNuVW0zdU1QdXFSQjZsMURh
            TzJZMVArOFRwS1RWallvQXRweEF0UjQKLS0tIHh3S3dOcmZ2c1l2OE1LZGNlN0Nz
            cEY1a3pzWkc0aEdycjB6UXZJUnNLOU0KJ810MPSV+AHEJf1mWJu4aKG6GjbF3D+k
            xcmFwk9z1vxB8CEybn4WKXi2yyj9I+iy+Rnz5pT+cep3hKYclRm36Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10jl78vwyqk622dpn2890l9jl4et3p7lsr8wh8vusem3j8jdxle8qg000qa
    lastmodified: "2026-08-23T09:34:36Z"
    mac: ENC[AES256_GCM,data:jJLWXYEl0YpYqnfi7nesemuiszbRLS1VaZfXA8sB4k4mcamYrPUDrOtV4LKd1XJLE3YWSKAC3T5RIuiu9sQyCBzauUUc9MAcxZEsEviKOAKFLsNGrz9keBeXmloy1ZpkNFFd1UvAoOvskypp7DtFKg21n4ssZd0OL+M1Mt1W9CE=,iv:vbD2nySLQzLqYq0ZDZzG5RwKA6Z1xuX8sWEFSBKd3vk=,tag:Y1KrAnoQjqXG85I0qd/ZZQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
