restic: ENC[AES256_GCM,data:L1S0WEBMbr3gQA==,iv:9NdaTuhLR57mv8OaCSyso9cfr8V1iQNuQuWInKyi3bI=,tag:L2H0EeCxx6hGk85Z+ObShg==,type:str]
traefik: ENC[AES256_GCM,data:MuG+NilIrc8FOh/H5ze81S12rd4ORFaJLVJ4kuDxGjwOhM71muxGw26/NVsUKHPSOL6VLePENZ7fpZ28PuzR1DwQYF4j6Ltlpci7RLAsEKdxYg==,iv:ZL90s3YuBmwafBz7VEwCTr2flnkguUxJgPp9OrnyfGA=,tag:lEkO4UN5s3n3ZUxNwSg7Jw==,type:str]
warden: ENC[AES256_GCM,data:uLWCQ/w0FqyGKvCBp0Z6wpYgvQzZDRYHCBNrKqFA9ykwglPEvN60WnQJdhmLDHpdfeWVSlldkC74m3msQ3SAItYtu8jBN5LJi4ns5gQvbR1PaZ6BnPQnzAYPGEMbKjT9p02OVXs9ZxGExYqn4quZj6auvIl/ZD0OBikP+SSLjtC/2lyCeCOdN0q31xU7dGeEOl+pZp/KxeJIrKl7/vsxLRIhzat6UL2e2mnE/HBrGrxkkvU23/QJChpPoX3gEvnwLFtt0JBh3KCdSVSJ+iBSm+FJ/E6kYeRJ6JHAmXXQZu1tbrzyLoWf2ua26xtYRYL5k9Y5WDIy/otFQnw=,iv:OauSp63ywmrkENIqBVGVQ99Ozyom0o+DfSqYaL46Ujg=,tag:aWpRcFPIcCxW73ztvOk4mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYmVvZm13amgwLzBOSmtE
            Q0hrNFFlZ0gwZ2RvTmFDSHgrQVJMMjUwckJVCkxrQWVQVXVCT0d0V0l6WDM5UjEv
            RDd6eHBnbHd6ZU51ZzIvQmFXT1VwY00KLS0tIC9EeDJJT0RpWmI4aGw5ek16QVhs
            dEtjc2hZM25lY1luOVZwUjVqRWJ4cmsK0w53owK2lhMFRY/NljyTOkeMUgp3Wab/
            83g/SrFTmdI0rNIHpBAQSEHOYi2J/4O2+BRd8fbtdsFDJsS4A0cOQA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jl78vwyqk622dpn2890l9jl4et3p7lsr8wh8vusem3j8jdxle8qg000qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrS3BlcnAzdkM5MkJMVS9F
            dzFvZ3NHZzVrTnNFdlE2Ni9tY1NuYXRhY0dVCmNQVi83dW9ld1JjVnNTdTBaNUVQ
            a2tJRlFLRndVQVEzVWhaK0UrVWdyZEUKLS0tIDk4TEVzZllYNEZJNFZyR0dGR0pY
            SUl2MVg1dm1DOVhGMkd1bXloZXltQUkKk1p+BMWj7RpRZSNgrGXtf4VS8MveRCrs
            qBqMVgAh7GpeSlBZ4Ip5T5b14D3QC08eD8rERJjn+LFUX9pQBjz5SA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T08:11:43Z"
    mac: ENC[AES256_GCM,data:jYrC74CR9aAMNbaKDKFnwTUusWpIVyh58JswO5hE5HZg0xZvtEi2+fXC+pK/fgdS8ADczYvDXO6SuhJgzLrihecGdpjQFK2HciyULpDOIBNplj06gF0KVn8Wl40gZCph6bjNnUG8rDEFsADjEbwdoW9UWhjcnd4wpDo3eLg93bQ=,iv:fDuFh18JRxyyoxQ/85RIC8DVbxDq3UkBgGlHpcYiJt8=,tag:Yx4EKxW5iGBkbUQkVw87dA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
