restic: ENC[AES256_GCM,data:4GMRW4Ptmk4tiw==,iv:9NdaTuhLR57mv8OaCSyso9cfr8V1iQNuQuWInKyi3bI=,tag:5nFx8ywZnVqJGt2SwP9x9g==,type:str]
rustic: ENC[AES256_GCM,data:7P+tEASLt2UeNkE=,iv:MXlQuvTJa2mZuXeiCX/YYpbqKpT1+RE5TNahBrUMM3Y=,tag:7d92K/keK1IImUmX6ooROA==,type:str]
rustic-user: ENC[AES256_GCM,data:H+neTmR1Ig==,iv:y0pbF5axrPRdYRGAmx+kp7jkmSl77R8LQMUKQaiDWak=,tag:1BpNPjhftBX0l7KXX8JqCg==,type:str]
traefik: ENC[AES256_GCM,data:WO2jsby46zgbXwluzqR3W6RzGHHzDmlB6cL0QJQnbvRAsLqNrdnurcElTV/BGK1stYxTA+K2wHlrcNTogDQ6BW3R8KBV1YW98M7sQfxddNpCWA==,iv:ZL90s3YuBmwafBz7VEwCTr2flnkguUxJgPp9OrnyfGA=,tag:H6ED39HSY/7jFQ7qtZA8dA==,type:str]
warden: ENC[AES256_GCM,data:g9/8XSl1coDMDKtk5TMBhcpCpVAUG/i8p+jNC739AQ6KCu4+YVPYeHzU4YIxR2SklHEcITL1lFd+B2AAgfjVABnq5WLy5XNZCMhdpxwxbvzQEPVKwQ+oGAcD7JtbFoTEfdR3oZJLb/wctroh8CeYJjYFdcgdFZmQy1K93Y+Wb1wD01hc3QeoBX/a6JXg2lm8O2TQWymi9Y4878y3byzGp3xiurXsJXZ8Rr4CWyw+qXIFrb7tiBLMNFHS0ceNlwXy9Frf5c5WRRbDSGSUimU6dzfuA8/wFsAKA+Fg6mIjkPQEcuA17wJdefKsRnUs2cNmG2EQqcZsU0ZItoY=,iv:OauSp63ywmrkENIqBVGVQ99Ozyom0o+DfSqYaL46Ujg=,tag:HIcihVncN5PoERd3BX3eRg==,type:str]
searx: ENC[AES256_GCM,data:KBsgR5uSYp+gA9ema6UD1vr2vvC6Oa8AVAIb0P1gAGaX+3mW59aUhCfsyKKEv7Xcpu/Gu8ou0Aa8jMQT7eynk7fQZ034E46bSrHOjE99vv8=,iv:TjSbP5Ej7RMzrZWNgrAwRsmeqOTzr7yOuvlcabSBXWI=,tag:5/EqQnCya9yYesAMlMPZjw==,type:str]
sops:
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaVBtR21udjExTzBRUFlF
            bmlESmRCR3RteXNMeHJMY3ByOHM5bE02a0hvCjJpbDhIRmNhWlNZNmpzRHMrWTY1
            SEZESGtGMk1NVzJZNkpnTWxSRG9IU2cKLS0tIDhpT1J6a0hSaVBvcDdJSE12TWVl
            bVo1c2Zwa2dxRmVZaHRqODEzLzg5Rk0KUSSZqgF032BbleFH2LkTfVnuF4wtSicc
            FHaqm+0LNHuAfSCdtrjZLqYEsUYKmnsqhePQbaMTyyQHKVEbFQt42Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jl78vwyqk622dpn2890l9jl4et3p7lsr8wh8vusem3j8jdxle8qg000qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQ283OEVGQXJhWU1YbTAv
            VFRueXpmRVJ3cmZqRTVLYjRqM2IrYjREaEM4Cm9haGZnbXNDL1JjQmhFZy82VkF2
            QkRDYVBDRHpoajhPOHRpeld5WGVqdjAKLS0tIDkyaDJhQUV4Zi9rd1RTa0xCQ2RG
            SUdPR3dVWG54RElsRkI4N2gyQk5aYW8KewBQi6+lLLK017UtWwMi5s6JVYzrZSfV
            vIrPB+/AqyTu9sc0hOHHLCVsTaQ+p2fRrT4DnaGUf0K8mh5N+TaScQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T21:46:49Z"
    mac: ENC[AES256_GCM,data:BCShvIa7wTj9FFrCkjcIlRhb9dh0xdeiVaX0HCgO9O8TONwvG43QvnK5Zhg2w80LhVRq7yPqhTchXCJ+8qk0pJfQHTOW9q1ZSRL8kB8WxGSk56xuiiEnifmEnF+1naWbo7GdOvT6mEyUigLEgmT1SvPGXiyvn3LTsS6NmfluVXo=,iv:vShpE3a7DergfdRj32S88jFTFBvPdG1hPonHGjnSvAM=,tag:n8iYUMNRmHoXf8CZAVCPgQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
