restic: ENC[AES256_GCM,data:CoCgNPIOSG6UXw==,iv:9NdaTuhLR57mv8OaCSyso9cfr8V1iQNuQuWInKyi3bI=,tag:qYB3FWJlg6IZlj+hzI80Jw==,type:str]
traefik: ENC[AES256_GCM,data:Z8KLXUR/upNTLvldlDwVHTPPajxqnAORUNYXsS73DJo78kpIwbWgrKtPiHWWCM4Jqq1qaFxiAyupg55Tatv1zJ3UKoBHDDi4sKIAuRy1Krwz3w==,iv:ZL90s3YuBmwafBz7VEwCTr2flnkguUxJgPp9OrnyfGA=,tag:1SBN3KV0agQB5F6H3E4WnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1wpwkf2g475umw3wwns57r8ucykvy6lflpc7uphs0mx9exsj04quqpy7t6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQXZTRjF0b0pIK1JxZUFt
            NHlPZzFUR0VTL1dUQTVPRXNESUJoRkw3MEc0Ci9qUjc2SmE2d3R1ckdBWjF4Q3RV
            UEtDSGI3VGVGNlJNc0xsU3BBVVZhM3MKLS0tIEtmODNrVGpDaEJ2K0ZyRk1GT08z
            ajFTR1NUSlc1NC9HVDlZWDM2MzdiTDgKOmYAKA/bOgAesezmYUHH+ZR/BFMyUqzp
            q3ORVxE8DAiPtc6MSREnO8saNKNMv18qVVY0SKPCyhWFYg4sLbnEng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age10jl78vwyqk622dpn2890l9jl4et3p7lsr8wh8vusem3j8jdxle8qg000qa
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBndStma1NtRzN4VWFSR0N1
            dlBGT2lrZkxzandzT2RBa3R4QmZNRkl1NTFFCkhNOGhsZjFhWmpLS2tzQWs0TC85
            cVhXQ1lrN05OalJRL29OenZaOHcyWUUKLS0tIG9FcVF0NzZERnV4V0pYM3VNVTJJ
            N2FoNkFKRDhZUE8xa29LVmJnTjUwUkUK+IiaSZycxZgl5GHoFom2Fs92gBQQZ/QO
            DepPksFFqqG9YW7V6c16ejMc7SNtt0szQwbmqoTviIadiv26+XS8Cw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-18T21:34:05Z"
    mac: ENC[AES256_GCM,data:DnWZuHwqq9TBFwnHo30E56NDCWBaf726YWEBE8jP9CbovicdnRjqyogdoVcns9fkcMg3v9kAQAm6Ndw+wNwdEGhXcUs0ZSvpJlYJ0vSns2N3V8PNs23ldhxCfRcLPklXxZgwU0FQNkokCDbmHWjDY+1HHfIwgGfDHNQMRbUClC8=,iv:Y1h03lQS7Pp37tIUKQVw9ViIK+oFbseRLGQ/ORfHEDo=,tag:EptI6j5/UQFCGPBLs1/QYg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
